# Generated by Django 5.2.11 on 2026-08-01 10:43

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0003_managerassignment_workforceassignment'),
        ('organizations', '0004_shiftroster_shiftrosterassignment_shiftrotation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier (UUIDv4) for entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the entity was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entity was last updated.')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when entity was soft-deleted, null if active.', null=True)),
                ('code', models.CharField(help_text='Unique project code within organization (e.g. PRJ-2026-001).', max_length=50)),
                ('name', models.CharField(help_text='Human-readable project name.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed project scope description.')),
                ('project_type', models.CharField(choices=[('INTERNAL', 'Internal Operational Project'), ('CLIENT', 'Client External Project'), ('DEPARTMENT', 'Departmental Initiative'), ('RESEARCH', 'Research & Development'), ('MAINTENANCE', 'System & Operations Maintenance'), ('AUTOMATION', 'Process Automation Project'), ('AI', 'Artificial Intelligence Initiative'), ('CUSTOM', 'Custom Project Type')], default='INTERNAL', help_text='Classification of project type.', max_length=50)),
                ('category', models.CharField(choices=[('SOFTWARE', 'Software Engineering'), ('MARKETING', 'Marketing Campaign'), ('HR', 'Human Resources Initiative'), ('FINANCE', 'Finance & Accounting'), ('OPERATIONS', 'Business Operations'), ('INFRASTRUCTURE', 'IT Infrastructure'), ('RESEARCH', 'Research & Innovation'), ('CLIENT_DELIVERY', 'Client Delivery Services'), ('CUSTOM', 'Custom Category')], default='SOFTWARE', help_text='Business category.', max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft Proposal'), ('PLANNING', 'Project Planning'), ('APPROVED', 'Approved for Execution'), ('IN_PROGRESS', 'In Progress'), ('ON_HOLD', 'On Hold / Paused'), ('COMPLETED', 'Completed Successfully'), ('CANCELLED', 'Cancelled'), ('ARCHIVED', 'Archived')], default='DRAFT', help_text='Lifecycle status.', max_length=50)),
                ('priority', models.CharField(choices=[('LOW', 'Low Priority'), ('MEDIUM', 'Medium Priority'), ('HIGH', 'High Priority'), ('URGENT', 'Urgent Priority'), ('CRITICAL', 'Critical Enterprise Priority')], default='MEDIUM', help_text='Execution priority.', max_length=50)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk'), ('CRITICAL', 'Critical Risk')], default='LOW', help_text='Assessed risk level.', max_length=50)),
                ('visibility', models.CharField(choices=[('PRIVATE', 'Private to Assigned Members'), ('INTERNAL', 'Visible to Department'), ('ORGANIZATION', 'Visible to Entire Organization'), ('CLIENT', 'Visible to Client Stakeholders')], default='ORGANIZATION', help_text='Visibility scope.', max_length=50)),
                ('start_date', models.DateField(blank=True, help_text='Planned start date.', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Planned target completion date.', null=True)),
                ('estimated_budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Estimated total budget.', max_digits=16)),
                ('estimated_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Estimated total effort hours.', max_digits=12)),
                ('is_active', models.BooleanField(default=True, help_text='Whether project is active.')),
                ('is_archived', models.BooleanField(default=False, help_text='Whether project is archived.')),
                ('settings_json', models.JSONField(blank=True, default=dict, help_text='Project configuration settings (calendar, working days, timezone, task prefix).')),
                ('branch', models.ForeignKey(blank=True, help_text='Associated branch location if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='organizations.branch')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, help_text='Associated department if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='organizations.department')),
                ('manager', models.ForeignKey(help_text='Designated project manager.', on_delete=django.db.models.deletion.PROTECT, related_name='managed_projects', to='employees.employee')),
                ('organization', models.ForeignKey(help_text='Owning organization.', on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='organizations.organization')),
                ('owner', models.ForeignKey(help_text='Executive project owner.', on_delete=django.db.models.deletion.PROTECT, related_name='owned_projects', to='employees.employee')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier (UUIDv4) for entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the entity was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entity was last updated.')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when entity was soft-deleted, null if active.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('actor_user_id', models.CharField(blank=True, help_text='User ID who performed action.', max_length=100)),
                ('action', models.CharField(help_text='Action key (e.g. PROJECT_CREATED, PROJECT_ACTIVATED).', max_length=100)),
                ('description', models.TextField(help_text='Human-readable log description.')),
                ('changes_json', models.JSONField(blank=True, default=dict, help_text='Delta payload of modified fields.')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(help_text='Target project.', on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project Audit Log',
                'verbose_name_plural': 'Project Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier (UUIDv4) for entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the entity was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entity was last updated.')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when entity was soft-deleted, null if active.', null=True)),
                ('role', models.CharField(choices=[('OWNER', 'Project Executive Owner'), ('MANAGER', 'Project Manager'), ('TEAM_LEAD', 'Technical / Team Lead'), ('DEVELOPER', 'Software Engineer / Developer'), ('QA', 'Quality Assurance Specialist'), ('DESIGNER', 'UI/UX Designer'), ('BUSINESS_ANALYST', 'Business Analyst'), ('OBSERVER', 'Stakeholder / Observer'), ('CUSTOM', 'Custom Project Role')], default='DEVELOPER', help_text='Project member role.', max_length=50)),
                ('allocated_hours_per_week', models.DecimalField(decimal_places=2, default=Decimal('40.00'), help_text='Weekly allocated capacity hours.', max_digits=5)),
                ('joined_at', models.DateField(auto_now_add=True, help_text='Date member joined project.')),
                ('left_at', models.DateField(blank=True, help_text='Date member left project if unassigned.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether member assignment is active.')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(help_text='Assigned employee.', on_delete=django.db.models.deletion.PROTECT, related_name='project_assignments', to='employees.employee')),
                ('project', models.ForeignKey(help_text='Assigned project.', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project Member',
                'verbose_name_plural': 'Project Members',
            },
        ),
        migrations.CreateModel(
            name='ProjectTeam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier (UUIDv4) for entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the entity was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entity was last updated.')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when entity was soft-deleted, null if active.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('name', models.CharField(help_text='Team name (e.g. Frontend Team, Core Backend).', max_length=150)),
                ('description', models.TextField(blank=True, help_text='Team description and responsibilities.')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(help_text='Associated project.', on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project Team',
                'verbose_name_plural': 'Project Teams',
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['organization', 'status'], name='idx_project_org_status'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['organization', 'project_type'], name='idx_project_org_type'),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('organization', 'code')},
        ),
        migrations.AddIndex(
            model_name='projectmember',
            index=models.Index(fields=['project', 'is_active'], name='idx_projmem_proj_active'),
        ),
        migrations.AlterUniqueTogether(
            name='projectmember',
            unique_together={('project', 'employee')},
        ),
    ]
