# Generated by Django 5.2.11 on 2026-08-01 10:49

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_managerassignment_workforceassignment'),
        ('organizations', '0004_shiftroster_shiftrosterassignment_shiftrotation_and_more'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier (UUIDv4) for entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the entity was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entity was last updated.')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when entity was soft-deleted, null if active.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('code', models.CharField(help_text='Unique task code within project (e.g. PRJ-NEX-12).', max_length=50)),
                ('wbs_code', models.CharField(blank=True, help_text='Hierarchical WBS numbering code (e.g. 1.2.1).', max_length=50)),
                ('title', models.CharField(help_text='Task title.', max_length=250)),
                ('description', models.TextField(blank=True, help_text='Detailed task specification.')),
                ('task_type', models.CharField(choices=[('EPIC', 'Epic Parent Container'), ('STORY', 'User Story'), ('TASK', 'Standard Work Task'), ('SUBTASK', 'Subtask Work Unit'), ('BUG', 'Defect / Software Bug'), ('ISSUE', 'Operational Issue'), ('FEATURE', 'Feature Request'), ('SPIKE', 'Technical Research Spike'), ('RESEARCH', 'Research Initiative'), ('IMPROVEMENT', 'System Improvement'), ('CUSTOM', 'Custom Task Type')], default='TASK', help_text='Classification of task type.', max_length=50)),
                ('status', models.CharField(choices=[('BACKLOG', 'Backlog'), ('TODO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('IN_REVIEW', 'Under Peer Review'), ('BLOCKED', 'Blocked by Dependency'), ('DONE', 'Completed / Done'), ('CANCELLED', 'Cancelled'), ('ARCHIVED', 'Archived')], default='TODO', help_text='Current execution status.', max_length=50)),
                ('priority', models.CharField(choices=[('LOW', 'Low Priority'), ('MEDIUM', 'Medium Priority'), ('HIGH', 'High Priority'), ('URGENT', 'Urgent Priority'), ('CRITICAL', 'Critical Enterprise Priority')], default='MEDIUM', help_text='Priority level.', max_length=50)),
                ('severity', models.CharField(choices=[('TRIVIAL', 'Trivial Impact'), ('MINOR', 'Minor Impact'), ('MAJOR', 'Major Impact'), ('CRITICAL', 'Critical Impact'), ('BLOCKER', 'System Blocker')], default='MINOR', help_text='Impact severity.', max_length=50)),
                ('story_points', models.DecimalField(decimal_places=1, default=Decimal('0.0'), help_text='Agile story points effort estimate.', max_digits=5)),
                ('estimated_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Estimated effort hours.', max_digits=8)),
                ('actual_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Actual logged effort hours.', max_digits=8)),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated progress percentage (0.00 - 100.00).', max_digits=5)),
                ('start_date', models.DateField(blank=True, help_text='Planned start date.', null=True)),
                ('due_date', models.DateField(blank=True, help_text='Target due date.', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp when task reached DONE status.', null=True)),
                ('is_archived', models.BooleanField(default=False, help_text='Whether task is archived.')),
                ('assignee', models.ForeignKey(blank=True, help_text='Primary assigned employee.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='employees.employee')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('epic', models.ForeignKey(blank=True, help_text='Associated parent epic if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='epic_tasks', to='projects.task')),
                ('organization', models.ForeignKey(help_text='Owning organization.', on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='organizations.organization')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent task for WBS hierarchical decomposition.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='projects.task')),
                ('project', models.ForeignKey(help_text='Associated project.', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project')),
                ('reporter', models.ForeignKey(help_text='Employee who reported or created task.', on_delete=django.db.models.deletion.PROTECT, related_name='reported_tasks', to='employees.employee')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
        migrations.CreateModel(
            name='TaskActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier (UUIDv4) for entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the entity was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entity was last updated.')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when entity was soft-deleted, null if active.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('actor_user_id', models.CharField(blank=True, help_text='User ID of actor.', max_length=100)),
                ('action', models.CharField(help_text='Action key (e.g. TASK_CREATED, STATUS_CHANGED, ASSIGNED).', max_length=100)),
                ('description', models.TextField(help_text='Human-readable log entry.')),
                ('metadata_json', models.JSONField(blank=True, default=dict, help_text='Delta parameters of activity.')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(help_text='Target task.', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='projects.task')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task Activity Log',
                'verbose_name_plural': 'Task Activity Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier (UUIDv4) for entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the entity was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entity was last updated.')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when entity was soft-deleted, null if active.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('role', models.CharField(choices=[('ASSIGNEE', 'Primary Assignee'), ('REVIEWER', 'Peer Reviewer'), ('APPROVER', 'Final Approver'), ('OBSERVER', 'Stakeholder Observer')], default='ASSIGNEE', help_text='Assignment role.', max_length=50)),
                ('assigned_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of assignment.')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(help_text='Assigned employee.', on_delete=django.db.models.deletion.PROTECT, related_name='task_assignments', to='employees.employee')),
                ('task', models.ForeignKey(help_text='Assigned task.', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='projects.task')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task Assignment',
                'verbose_name_plural': 'Task Assignments',
            },
        ),
        migrations.CreateModel(
            name='TaskChecklist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier (UUIDv4) for entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the entity was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entity was last updated.')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when entity was soft-deleted, null if active.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('title', models.CharField(help_text='Checklist item title.', max_length=200)),
                ('is_completed', models.BooleanField(default=False, help_text='Whether checklist item is marked completed.')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp when completed.', null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(help_text='Target task.', on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='projects.task')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task Checklist Item',
                'verbose_name_plural': 'Task Checklist Items',
            },
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier (UUIDv4) for entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the entity was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entity was last updated.')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when entity was soft-deleted, null if active.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('author_user_id', models.CharField(help_text='User ID of comment author.', max_length=100)),
                ('author_name', models.CharField(help_text='Display name of comment author.', max_length=150)),
                ('content', models.TextField(help_text='Comment text body.')),
                ('is_internal_note', models.BooleanField(default=False, help_text='Whether comment is restricted to internal team.')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('parent_comment', models.ForeignKey(blank=True, help_text='Parent comment for threaded replies.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='projects.taskcomment')),
                ('task', models.ForeignKey(help_text='Target task.', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='projects.task')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task Comment',
                'verbose_name_plural': 'Task Comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskDependency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier (UUIDv4) for entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the entity was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entity was last updated.')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when entity was soft-deleted, null if active.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('dependency_type', models.CharField(choices=[('FINISH_TO_START', 'Finish-to-Start (FS)'), ('START_TO_START', 'Start-to-Start (SS)'), ('FINISH_TO_FINISH', 'Finish-to-Finish (FF)'), ('START_TO_FINISH', 'Start-to-Finish (SF)')], default='FINISH_TO_START', help_text='Type of dependency linkage.', max_length=50)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('source_task', models.ForeignKey(help_text='Source predecessor task.', on_delete=django.db.models.deletion.CASCADE, related_name='predecessor_dependencies', to='projects.task')),
                ('target_task', models.ForeignKey(help_text='Target successor task.', on_delete=django.db.models.deletion.CASCADE, related_name='successor_dependencies', to='projects.task')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task Dependency',
                'verbose_name_plural': 'Task Dependencies',
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'status'], name='idx_task_proj_status'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'task_type'], name='idx_task_proj_type'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['parent', 'wbs_code'], name='idx_task_parent_wbs'),
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('project', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='taskassignment',
            unique_together={('task', 'employee', 'role')},
        ),
        migrations.AlterUniqueTogether(
            name='taskdependency',
            unique_together={('source_task', 'target_task')},
        ),
    ]
