# Generated by Django 5.2.11 on 2026-08-01 11:00

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_managerassignment_workforceassignment'),
        ('organizations', '0004_shiftroster_shiftrosterassignment_shiftrotation_and_more'),
        ('projects', '0002_task_taskactivitylog_taskassignment_taskchecklist_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='backlog_rank',
            field=models.PositiveIntegerField(default=0, help_text='Product backlog sequence ranking order.'),
        ),
        migrations.CreateModel(
            name='BoardColumn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier (UUIDv4) for entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the entity was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entity was last updated.')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when entity was soft-deleted, null if active.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('name', models.CharField(help_text='Column header (e.g. In Review).', max_length=100)),
                ('order', models.PositiveIntegerField(default=1, help_text='Display sequence order.')),
                ('wip_limit', models.PositiveIntegerField(default=0, help_text='Maximum Work-In-Progress card capacity (0 = unlimited).')),
                ('mapped_status', models.CharField(choices=[('BACKLOG', 'Backlog'), ('TODO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('IN_REVIEW', 'Under Peer Review'), ('BLOCKED', 'Blocked by Dependency'), ('DONE', 'Completed / Done'), ('CANCELLED', 'Cancelled'), ('ARCHIVED', 'Archived')], default='TODO', help_text='Task status mapped to this column.', max_length=50)),
                ('policy_description', models.TextField(blank=True, help_text='Definition of Done / Entry policy for column.')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Board Column',
                'verbose_name_plural': 'Board Columns',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='board_column',
            field=models.ForeignKey(blank=True, help_text='Current Kanban board column.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='projects.boardcolumn'),
        ),
        migrations.CreateModel(
            name='KanbanBoard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier (UUIDv4) for entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the entity was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entity was last updated.')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when entity was soft-deleted, null if active.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('name', models.CharField(help_text='Board title (e.g. Main Engineering Kanban).', max_length=150)),
                ('board_type', models.CharField(choices=[('SCRUM', 'Scrum Board'), ('KANBAN', 'Kanban Board'), ('HYBRID', 'Scrumban / Hybrid Board')], default='KANBAN', help_text='Board workflow type.', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Board description.')),
                ('estimation_scale', models.CharField(choices=[('FIBONACCI', 'Fibonacci Scale (1, 2, 3, 5, 8, 13, 21)'), ('T_SHIRT', 'T-Shirt Sizes (XS, S, M, L, XL)'), ('HOURS', 'Direct Hourly Effort'), ('CUSTOM', 'Custom Scale')], default='FIBONACCI', help_text='Estimation scale used on board.', max_length=50)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='Owning organization.', on_delete=django.db.models.deletion.PROTECT, related_name='boards', to='organizations.organization')),
                ('project', models.ForeignKey(help_text='Associated project.', on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kanban Board',
                'verbose_name_plural': 'Kanban Boards',
            },
        ),
        migrations.AddField(
            model_name='boardcolumn',
            name='board',
            field=models.ForeignKey(help_text='Parent board.', on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='projects.kanbanboard'),
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier (UUIDv4) for entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the entity was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entity was last updated.')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when entity was soft-deleted, null if active.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('name', models.CharField(help_text='Release name (e.g. Version 2.5.0 - Enterprise).', max_length=150)),
                ('version', models.CharField(help_text='SemVer version code (e.g. v2.5.0).', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Release notes summary.')),
                ('target_date', models.DateField(blank=True, help_text='Planned release date.', null=True)),
                ('released_at', models.DateField(blank=True, help_text='Actual release date.', null=True)),
                ('is_released', models.BooleanField(default=False, help_text='Whether release is published.')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='Owning organization.', on_delete=django.db.models.deletion.PROTECT, related_name='releases', to='organizations.organization')),
                ('project', models.ForeignKey(help_text='Associated project.', on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Release',
                'verbose_name_plural': 'Releases',
            },
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier (UUIDv4) for entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the entity was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entity was last updated.')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when entity was soft-deleted, null if active.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('sprint_number', models.PositiveIntegerField(help_text='Sequential sprint number within project.')),
                ('name', models.CharField(help_text='Sprint title (e.g. Sprint 12 - Core Engine).', max_length=150)),
                ('goal', models.TextField(blank=True, help_text='Sprint business goal statement.')),
                ('sprint_type', models.CharField(choices=[('REGULAR', 'Regular Scrum Sprint'), ('ITERATION', 'Development Iteration'), ('RELEASE', 'Release Stabilization Sprint'), ('PLANNING', 'PI / Sprint Planning'), ('HARDENING', 'Security / Hardening Sprint'), ('CUSTOM', 'Custom Sprint')], default='REGULAR', help_text='Sprint classification.', max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft / Unplanned'), ('PLANNING', 'In Planning'), ('ACTIVE', 'Active / In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', help_text='Current sprint lifecycle status.', max_length=50)),
                ('start_date', models.DateField(help_text='Planned start date.')),
                ('end_date', models.DateField(help_text='Planned end date.')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Actual completion timestamp.', null=True)),
                ('capacity_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total team effort capacity in hours.', max_digits=8)),
                ('total_story_points', models.DecimalField(decimal_places=1, default=Decimal('0.0'), help_text='Total committed story points.', max_digits=8)),
                ('completed_story_points', models.DecimalField(decimal_places=1, default=Decimal('0.0'), help_text='Actual completed story points at sprint close.', max_digits=8)),
                ('velocity', models.DecimalField(decimal_places=1, default=Decimal('0.0'), help_text='Calculated velocity for sprint.', max_digits=8)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='Owning organization.', on_delete=django.db.models.deletion.PROTECT, related_name='sprints', to='organizations.organization')),
                ('owner', models.ForeignKey(help_text='Scrum Master / Sprint Owner.', on_delete=django.db.models.deletion.PROTECT, related_name='owned_sprints', to='employees.employee')),
                ('project', models.ForeignKey(help_text='Associated project.', on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='projects.project')),
                ('team', models.ForeignKey(blank=True, help_text='Assigned project team if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sprints', to='projects.projectteam')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sprint',
                'verbose_name_plural': 'Sprints',
                'ordering': ['-sprint_number'],
                'unique_together': {('project', 'sprint_number')},
            },
        ),
        migrations.AddField(
            model_name='task',
            name='sprint',
            field=models.ForeignKey(blank=True, help_text='Assigned Sprint container.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='projects.sprint'),
        ),
    ]
