# Generated by Django 5.2.11 on 2026-08-01 11:05

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_managerassignment_workforceassignment'),
        ('organizations', '0004_shiftroster_shiftrosterassignment_shiftrotation_and_more'),
        ('projects', '0003_task_backlog_rank_boardcolumn_task_board_column_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier (UUIDv4) for entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the entity was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entity was last updated.')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when entity was soft-deleted, null if active.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('period_type', models.CharField(choices=[('DAILY', 'Daily Timesheet'), ('WEEKLY', 'Weekly Timesheet'), ('BIWEEKLY', 'Biweekly Timesheet'), ('MONTHLY', 'Monthly Timesheet')], default='WEEKLY', help_text='Timesheet period frequency.', max_length=50)),
                ('start_date', models.DateField(help_text='Period start date.')),
                ('end_date', models.DateField(help_text='Period end date.')),
                ('total_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total logged hours in period.', max_digits=7)),
                ('billable_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total billable hours.', max_digits=7)),
                ('non_billable_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total non-billable hours.', max_digits=7)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated overtime hours.', max_digits=7)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted for Approval'), ('APPROVED', 'Approved by Manager'), ('REJECTED', 'Rejected'), ('LOCKED', 'Locked for Payroll / Invoicing')], default='DRAFT', help_text='Current timesheet approval status.', max_length=50)),
                ('submitted_at', models.DateTimeField(blank=True, help_text='Submission timestamp.', null=True)),
                ('approved_at', models.DateTimeField(blank=True, help_text='Approval timestamp.', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Rejection comments if rejected.')),
                ('approver', models.ForeignKey(blank=True, help_text='Approving manager employee.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_timesheets', to='employees.employee')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(help_text='Submitting employee.', on_delete=django.db.models.deletion.PROTECT, related_name='timesheets', to='employees.employee')),
                ('organization', models.ForeignKey(help_text='Owning organization.', on_delete=django.db.models.deletion.PROTECT, related_name='timesheets', to='organizations.organization')),
                ('project', models.ForeignKey(blank=True, help_text='Associated project if project-specific timesheet.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timesheets', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Timesheet',
                'verbose_name_plural': 'Timesheets',
                'ordering': ['-start_date'],
                'unique_together': {('employee', 'period_type', 'start_date')},
            },
        ),
        migrations.CreateModel(
            name='TimesheetApprovalLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier (UUIDv4) for entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the entity was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entity was last updated.')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when entity was soft-deleted, null if active.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('actor_user_id', models.CharField(help_text='User ID of actor.', max_length=100)),
                ('action', models.CharField(help_text='Action key (e.g. SUBMITTED, APPROVED, REJECTED).', max_length=50)),
                ('comments', models.TextField(blank=True, help_text='Action approval / rejection comments.')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('timesheet', models.ForeignKey(help_text='Target timesheet.', on_delete=django.db.models.deletion.CASCADE, related_name='approval_logs', to='projects.timesheet')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Timesheet Approval Log',
                'verbose_name_plural': 'Timesheet Approval Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OvertimeRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier (UUIDv4) for entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the entity was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entity was last updated.')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when entity was soft-deleted, null if active.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('date', models.DateField(help_text='Date of overtime.')),
                ('regular_hours', models.DecimalField(decimal_places=2, default=Decimal('8.00'), help_text='Regular work hours.', max_digits=5)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Overtime hours logged.', max_digits=5)),
                ('category', models.CharField(choices=[('REGULAR_HOURS', 'Standard Work Hours'), ('DAILY_OVERTIME', 'Daily Overtime'), ('WEEKLY_OVERTIME', 'Weekly Overtime'), ('WEEKEND_OVERTIME', 'Weekend Overtime'), ('HOLIDAY_OVERTIME', 'Public Holiday Overtime')], default='DAILY_OVERTIME', help_text='Overtime category classification.', max_length=50)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(help_text='Target employee.', on_delete=django.db.models.deletion.PROTECT, related_name='overtime_records', to='employees.employee')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Overtime Record',
                'verbose_name_plural': 'Overtime Records',
                'unique_together': {('employee', 'date', 'category')},
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier (UUIDv4) for entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the entity was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entity was last updated.')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when entity was soft-deleted, null if active.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('entry_type', models.CharField(choices=[('MANUAL', 'Manual Worklog Entry'), ('TIMER', 'Live Start/Stop Timer'), ('BULK_IMPORT', 'Bulk Import Entry')], default='MANUAL', help_text='Type of time entry.', max_length=50)),
                ('billable_type', models.CharField(choices=[('BILLABLE', 'Client Billable Hours'), ('NON_BILLABLE', 'Non-Billable Work'), ('INTERNAL', 'Internal Project Hours'), ('TRAINING', 'Professional Development / Training'), ('MEETING', 'Client / Internal Meeting'), ('RESEARCH', 'R&D Research Hours')], default='BILLABLE', help_text='Billable classification.', max_length=50)),
                ('date', models.DateField(help_text='Worklog date.')),
                ('hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Logged effort hours (e.g. 2.50).', max_digits=5)),
                ('start_time', models.DateTimeField(blank=True, help_text='Start timestamp if timer entry.', null=True)),
                ('end_time', models.DateTimeField(blank=True, help_text='End timestamp if timer entry.', null=True)),
                ('is_timer_running', models.BooleanField(default=False, help_text='Whether live timer is actively running for employee.')),
                ('timer_started_at', models.DateTimeField(blank=True, help_text='Timestamp when live timer started.', null=True)),
                ('notes', models.TextField(blank=True, help_text='Detailed activity description notes.')),
                ('is_approved', models.BooleanField(default=False, help_text='Whether entry is approved via timesheet.')),
                ('is_locked', models.BooleanField(default=False, help_text='Whether entry is locked for payroll/invoicing.')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(help_text='Employee logging time.', on_delete=django.db.models.deletion.PROTECT, related_name='time_entries', to='employees.employee')),
                ('organization', models.ForeignKey(help_text='Owning organization.', on_delete=django.db.models.deletion.PROTECT, related_name='time_entries', to='organizations.organization')),
                ('project', models.ForeignKey(help_text='Associated project.', on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='projects.project')),
                ('sprint', models.ForeignKey(blank=True, help_text='Associated sprint if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries', to='projects.sprint')),
                ('task', models.ForeignKey(help_text='Associated task.', on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='projects.task')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Time Entry',
                'verbose_name_plural': 'Time Entries',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['employee', 'date'], name='idx_tentry_emp_date'), models.Index(fields=['project', 'date'], name='idx_tentry_proj_date'), models.Index(fields=['employee', 'is_timer_running'], name='idx_tentry_emp_timer')],
            },
        ),
    ]
