# Generated by Django 5.2.11 on 2026-08-01 11:11

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_managerassignment_workforceassignment'),
        ('organizations', '0004_shiftroster_shiftrosterassignment_shiftrotation_and_more'),
        ('projects', '0004_timesheet_timesheetapprovallog_overtimerecord_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceCapacitySnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier (UUIDv4) for entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the entity was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entity was last updated.')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when entity was soft-deleted, null if active.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('period_start', models.DateField(help_text='Snapshot period start.')),
                ('period_end', models.DateField(help_text='Snapshot period end.')),
                ('planned_capacity_hours', models.DecimalField(decimal_places=2, default=Decimal('160.00'), help_text='Total available working hours in period.', max_digits=7)),
                ('allocated_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total allocated hours across projects.', max_digits=7)),
                ('actual_logged_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Actual worklog hours logged.', max_digits=7)),
                ('utilization_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Utilization percentage (0 - 100+ %).', max_digits=5)),
                ('workload_status', models.CharField(choices=[('UNDERUTILIZED', 'Underutilized (< 50% capacity)'), ('OPTIMAL', 'Optimal Utilization (50% - 100% capacity)'), ('OVERALLOCATED', 'Overallocated (> 100% capacity)')], default='OPTIMAL', help_text='Workload utilization classification.', max_length=50)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(help_text='Target employee.', on_delete=django.db.models.deletion.PROTECT, related_name='capacity_snapshots', to='employees.employee')),
                ('organization', models.ForeignKey(help_text='Owning organization.', on_delete=django.db.models.deletion.PROTECT, related_name='capacity_snapshots', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resource Capacity Snapshot',
                'verbose_name_plural': 'Resource Capacity Snapshots',
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='ResourceSkillRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier (UUIDv4) for entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the entity was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entity was last updated.')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when entity was soft-deleted, null if active.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('skill_name', models.CharField(help_text='Skill name (e.g. Python, React, PostgreSQL).', max_length=100)),
                ('min_proficiency_level', models.IntegerField(default=3, help_text='Minimum required proficiency scale (1-5).')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='Owning organization.', on_delete=django.db.models.deletion.PROTECT, related_name='skill_requirements', to='organizations.organization')),
                ('project', models.ForeignKey(help_text='Target project.', on_delete=django.db.models.deletion.CASCADE, related_name='skill_requirements', to='projects.project')),
                ('task', models.ForeignKey(blank=True, help_text='Optional target task.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill_requirements', to='projects.task')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resource Skill Requirement',
                'verbose_name_plural': 'Resource Skill Requirements',
                'ordering': ['skill_name'],
            },
        ),
        migrations.CreateModel(
            name='ResourceAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier (UUIDv4) for entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the entity was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entity was last updated.')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when entity was soft-deleted, null if active.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('allocation_type', models.CharField(choices=[('PROJECT', 'Project Allocation'), ('TASK', 'Task Allocation'), ('TEAM', 'Team Level Reservation'), ('BENCH', 'Bench Reservation'), ('TRAINING', 'Training Allocation')], default='PROJECT', help_text='Type of allocation.', max_length=50)),
                ('allocation_percentage', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Allocation percentage (e.g. 50.00 for 50%).', max_digits=5)),
                ('allocated_hours_per_day', models.DecimalField(decimal_places=2, default=Decimal('8.00'), help_text='Daily planned capacity hours (e.g. 4.00h).', max_digits=4)),
                ('start_date', models.DateField(help_text='Allocation start date.')),
                ('end_date', models.DateField(help_text='Allocation end date.')),
                ('status', models.CharField(choices=[('RESERVED', 'Soft Reserved'), ('ACTIVE', 'Active Hard Allocation'), ('COMPLETED', 'Completed Allocation'), ('CANCELLED', 'Cancelled Allocation')], default='ACTIVE', help_text='Allocation status.', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Allocation assignment notes.')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(help_text='Allocated employee.', on_delete=django.db.models.deletion.PROTECT, related_name='resource_allocations', to='employees.employee')),
                ('organization', models.ForeignKey(help_text='Owning organization.', on_delete=django.db.models.deletion.PROTECT, related_name='resource_allocations', to='organizations.organization')),
                ('project', models.ForeignKey(help_text='Allocated project.', on_delete=django.db.models.deletion.CASCADE, related_name='resource_allocations', to='projects.project')),
                ('task', models.ForeignKey(blank=True, help_text='Optional specific task allocation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_allocations', to='projects.task')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resource Allocation',
                'verbose_name_plural': 'Resource Allocations',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['employee', 'start_date', 'end_date'], name='idx_resalloc_emp_dates'), models.Index(fields=['project', 'status'], name='idx_resalloc_proj_status')],
            },
        ),
    ]
