# Generated by Django 5.2.11 on 2026-08-01 11:19

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_managerassignment_workforceassignment'),
        ('organizations', '0004_shiftroster_shiftrosterassignment_shiftrotation_and_more'),
        ('projects', '0005_resourcecapacitysnapshot_resourceskillrequirement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier (UUIDv4) for entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the entity was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entity was last updated.')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when entity was soft-deleted, null if active.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('code', models.CharField(help_text='Unique portfolio code (e.g. PORT-STRAT-001).', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Portfolio name.', max_length=200)),
                ('portfolio_type', models.CharField(choices=[('STRATEGIC', 'Strategic Initiative Portfolio'), ('TECHNOLOGY', 'Technology & IT Portfolio'), ('CLIENT', 'Client Delivery Portfolio'), ('DEPARTMENT', 'Departmental Portfolio'), ('BUSINESS_UNIT', 'Business Unit Portfolio'), ('REGIONAL', 'Regional Operations Portfolio'), ('CUSTOM', 'Custom Portfolio')], default='STRATEGIC', help_text='Portfolio classification type.', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Portfolio strategic vision and objectives.')),
                ('budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total allocated portfolio budget.', max_digits=14)),
                ('priority', models.IntegerField(default=1, help_text='Strategic priority rank (1 = Highest).')),
                ('status', models.CharField(choices=[('PLANNING', 'In Planning'), ('ACTIVE', 'Active Portfolio'), ('ON_HOLD', 'On Hold'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], default='ACTIVE', help_text='Portfolio lifecycle status.', max_length=50)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('executive_sponsor', models.ForeignKey(blank=True, help_text='Executive C-level sponsor.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsored_portfolios', to='employees.employee')),
                ('organization', models.ForeignKey(help_text='Owning organization.', on_delete=django.db.models.deletion.PROTECT, related_name='portfolios', to='organizations.organization')),
                ('owner', models.ForeignKey(help_text='Portfolio owner / director.', on_delete=django.db.models.deletion.PROTECT, related_name='owned_portfolios', to='employees.employee')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolios',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier (UUIDv4) for entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the entity was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entity was last updated.')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when entity was soft-deleted, null if active.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('code', models.CharField(help_text='Unique program code (e.g. PRG-DIG-TRANS).', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Program name.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Program charter and objectives.')),
                ('budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Allocated program budget.', max_digits=14)),
                ('target_start_date', models.DateField(blank=True, help_text='Target start date.', null=True)),
                ('target_end_date', models.DateField(blank=True, help_text='Target completion date.', null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active Program'), ('IN_REVIEW', 'In Executive Review'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', help_text='Program lifecycle status.', max_length=50)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='Owning organization.', on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='organizations.organization')),
                ('portfolio', models.ForeignKey(blank=True, help_text='Parent strategic portfolio if mapped.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='projects.portfolio')),
                ('program_manager', models.ForeignKey(help_text='Designated program manager.', on_delete=django.db.models.deletion.PROTECT, related_name='managed_programs', to='employees.employee')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioRisk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier (UUIDv4) for entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the entity was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entity was last updated.')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when entity was soft-deleted, null if active.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('title', models.CharField(help_text='Risk summary title.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed risk description.')),
                ('probability', models.IntegerField(default=3, help_text='Probability scale (1 = Rare, 5 = Almost Certain).')),
                ('impact', models.IntegerField(default=3, help_text='Impact scale (1 = Negligible, 5 = Severe).')),
                ('risk_score', models.IntegerField(default=9, help_text='Calculated risk score (Probability * Impact: 1 - 25).')),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Severity Risk'), ('MEDIUM', 'Medium Severity Risk'), ('HIGH', 'High Severity Risk'), ('CRITICAL', 'Critical Enterprise Risk')], default='MEDIUM', help_text='Risk severity classification.', max_length=50)),
                ('status', models.CharField(choices=[('IDENTIFIED', 'Risk Identified'), ('ASSESSING', 'Under Assessment'), ('MITIGATING', 'Mitigation Plan Active'), ('CLOSED', 'Risk Closed / Resolved'), ('ESCALATED', 'Escalated to Executive PMO')], default='IDENTIFIED', help_text='Current risk status.', max_length=50)),
                ('mitigation_plan', models.TextField(blank=True, help_text='Actionable mitigation plan.')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='Owning organization.', on_delete=django.db.models.deletion.PROTECT, related_name='portfolio_risks', to='organizations.organization')),
                ('portfolio', models.ForeignKey(blank=True, help_text='Associated portfolio.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='projects.portfolio')),
                ('project', models.ForeignKey(blank=True, help_text='Associated project.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='projects.project')),
                ('risk_owner', models.ForeignKey(blank=True, help_text='Designated risk owner.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_risks', to='employees.employee')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(blank=True, help_text='Associated program.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='projects.program')),
            ],
            options={
                'verbose_name': 'Portfolio Risk',
                'verbose_name_plural': 'Portfolio Risks',
                'ordering': ['-risk_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioMilestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier (UUIDv4) for entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the entity was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entity was last updated.')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when entity was soft-deleted, null if active.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('title', models.CharField(help_text='Milestone title.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Milestone deliverables.')),
                ('target_date', models.DateField(help_text='Target delivery date.')),
                ('achieved_date', models.DateField(blank=True, help_text='Date milestone was achieved.', null=True)),
                ('is_completed', models.BooleanField(default=False, help_text='Whether milestone has been achieved.')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='Owning organization.', on_delete=django.db.models.deletion.PROTECT, related_name='portfolio_milestones', to='organizations.organization')),
                ('portfolio', models.ForeignKey(blank=True, help_text='Associated portfolio.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.portfolio')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(blank=True, help_text='Associated program.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.program')),
            ],
            options={
                'verbose_name': 'Portfolio Milestone',
                'verbose_name_plural': 'Portfolio Milestones',
                'ordering': ['target_date'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='program',
            field=models.ForeignKey(blank=True, help_text='Parent program if part of a program initiative.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.program'),
        ),
        migrations.CreateModel(
            name='PortfolioProjectMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier (UUIDv4) for entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the entity was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entity was last updated.')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when entity was soft-deleted, null if active.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('strategic_weight', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Strategic weighting in portfolio (e.g. 1.00).', max_digits=5)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('portfolio', models.ForeignKey(help_text='Target portfolio.', on_delete=django.db.models.deletion.CASCADE, related_name='project_mappings', to='projects.portfolio')),
                ('project', models.ForeignKey(help_text='Mapped project.', on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_mappings', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Portfolio Project Mapping',
                'verbose_name_plural': 'Portfolio Project Mappings',
                'unique_together': {('portfolio', 'project')},
            },
        ),
    ]
