"""Enterprise constants for the Leave Management Foundation Engine."""

DEFAULT_LEAVE_NOTICE_PERIOD_DAYS = 3
DEFAULT_MAX_CONSECUTIVE_LEAVE_DAYS = 15
DEFAULT_MIN_GAP_BETWEEN_LEAVES_DAYS = 0
DEFAULT_CARRY_FORWARD_EXPIRY_DAYS = 90
DEFAULT_MAX_CARRY_FORWARD_DAYS = 10
DEFAULT_ACCRUAL_CAP_DAYS = 30
DEFAULT_ATTACHMENT_THRESHOLD_DAYS = 3
