# Generated by Django 5.2.11 on 2026-08-01 06:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_email_verified_at_user_is_email_verified'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier (UUIDv4) for entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the entity was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entity was last updated.')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when entity was soft-deleted, null if active.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('token_hash', models.CharField(db_index=True, help_text='SHA-256 hash of single-use email verification token.', max_length=255, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True, help_text='Token expiration timestamp.')),
                ('is_used', models.BooleanField(db_index=True, default=False, help_text='Flag indicating whether token has already been consumed.')),
                ('used_at', models.DateTimeField(blank=True, help_text='Timestamp when token was consumed.', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address from which verification request originated.', null=True)),
                ('user_agent', models.TextField(blank=True, default='', help_text='User Agent verifying email.')),
            ],
            options={
                'verbose_name': 'email verification token',
                'verbose_name_plural': 'email verification tokens',
            },
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier (UUIDv4) for entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the entity was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entity was last updated.')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when entity was soft-deleted, null if active.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('email_attempted', models.EmailField(blank=True, db_index=True, default='', help_text='Email address attempted during authentication event.', max_length=255)),
                ('event_type', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('LOGOUT', 'Logout'), ('PASSWORD_RESET', 'Password Reset'), ('EMAIL_VERIFICATION', 'Email Verification'), ('ACCOUNT_LOCKED', 'Account Locked')], db_index=True, help_text='Category of authentication event.', max_length=50)),
                ('status', models.CharField(db_index=True, default='SUCCESS', help_text='Outcome status string.', max_length=20)),
                ('failure_reason', models.CharField(blank=True, default='', help_text='Description of failure reason if applicable.', max_length=255)),
                ('location', models.CharField(blank=True, default='', help_text='Geographic location estimate derived from IP.', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, help_text='Client IP address.', null=True)),
                ('user_agent', models.TextField(blank=True, default='', help_text='Full HTTP User-Agent string.')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Event timestamp.')),
            ],
            options={
                'verbose_name': 'login history',
                'verbose_name_plural': 'login histories',
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier (UUIDv4) for entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the entity was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entity was last updated.')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when entity was soft-deleted, null if active.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('token_hash', models.CharField(db_index=True, help_text='SHA-256 hash of single-use password reset token.', max_length=255, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True, help_text='Token expiration timestamp.')),
                ('is_used', models.BooleanField(db_index=True, default=False, help_text='Flag indicating whether token has already been consumed.')),
                ('used_at', models.DateTimeField(blank=True, help_text='Timestamp when token was consumed.', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address from which token request originated.', null=True)),
                ('user_agent', models.TextField(blank=True, default='', help_text='User Agent requesting password reset.')),
            ],
            options={
                'verbose_name': 'password reset token',
                'verbose_name_plural': 'password reset tokens',
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier (UUIDv4) for entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the entity was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entity was last updated.')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when entity was soft-deleted, null if active.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('language', models.CharField(default='en', help_text='Interface language locale.', max_length=10)),
                ('timezone', models.CharField(default='UTC', help_text='Primary operational timezone.', max_length=50)),
                ('theme', models.CharField(default='SYSTEM', help_text='Preferred UI theme code.', max_length=20)),
                ('email_notifications', models.BooleanField(default=True, help_text='Designates whether email notifications are enabled.')),
                ('push_notifications', models.BooleanField(default=True, help_text='Designates whether push notifications are enabled.')),
                ('two_factor_enabled', models.BooleanField(default=False, help_text='Designates whether two-factor authentication is active.')),
                ('extra_settings', models.JSONField(blank=True, default=dict, help_text='Extensible key-value preference configurations.')),
            ],
            options={
                'verbose_name': 'user preference',
                'verbose_name_plural': 'user preferences',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier (UUIDv4) for entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the entity was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entity was last updated.')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when entity was soft-deleted, null if active.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('bio', models.TextField(blank=True, default='', help_text='User biography summary.')),
                ('address', models.CharField(blank=True, default='', help_text='Street address.', max_length=255)),
                ('country', models.CharField(blank=True, db_index=True, default='', help_text='Country of residence.', max_length=100)),
                ('state', models.CharField(blank=True, default='', help_text='State, province, or region.', max_length=100)),
                ('city', models.CharField(blank=True, default='', help_text='City or municipality.', max_length=100)),
                ('postal_code', models.CharField(blank=True, default='', help_text='ZIP or postal code.', max_length=20)),
                ('website', models.URLField(blank=True, default='', help_text='Personal or business website URL.', max_length=255)),
                ('linkedin', models.URLField(blank=True, default='', help_text='LinkedIn profile URL.', max_length=255)),
                ('github', models.URLField(blank=True, default='', help_text='GitHub profile URL.', max_length=255)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private'), ('ORGANIZATION', 'Organization'), ('CONNECTIONS', 'Connections')], db_index=True, default='PUBLIC', help_text='Profile privacy visibility scope.', max_length=20)),
            ],
            options={
                'verbose_name': 'user profile',
                'verbose_name_plural': 'user profiles',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier (UUIDv4) for entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the entity was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entity was last updated.')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when entity was soft-deleted, null if active.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('jti', models.CharField(db_index=True, help_text='Unique JWT ID identifier.', max_length=255, unique=True)),
                ('refresh_token_hash', models.CharField(db_index=True, help_text='SHA-256 hash of refresh token value.', max_length=255)),
                ('access_token_expires_at', models.DateTimeField(help_text='Expiration timestamp of JWT access token.')),
                ('refresh_token_expires_at', models.DateTimeField(db_index=True, help_text='Expiration timestamp of JWT refresh token.')),
                ('location', models.CharField(blank=True, default='', help_text='Geographic location estimate derived from IP.', max_length=255)),
                ('browser', models.CharField(blank=True, default='', help_text='Client browser info.', max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Client IP address.', null=True)),
                ('login_time', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when session was initiated.')),
                ('last_activity', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Timestamp of last recorded session activity.')),
                ('logout_time', models.DateTimeField(blank=True, help_text='Timestamp when session was explicitly terminated.', null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked'), ('LOGGED_OUT', 'Logged Out')], db_index=True, default='ACTIVE', help_text='Current lifecycle status of session.', max_length=20)),
                ('is_current', models.BooleanField(default=False, help_text='Flag indicating whether this represents current user session.')),
            ],
            options={
                'verbose_name': 'user session',
                'verbose_name_plural': 'user sessions',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_email_verified',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.FileField(blank=True, help_text='Profile avatar image URL or file path.', max_length=512, null=True, upload_to='avatars/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='User date of birth.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when entity was soft-deleted, null if active.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, default='', help_text='Public display name.', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Designates whether user primary email has been verified.'),
        ),
        migrations.AddField(
            model_name='user',
            name='failed_login_attempts',
            field=models.PositiveIntegerField(default=0, help_text='Consecutive failed authentication attempts count.'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('PREFER_NOT_TO_SAY', 'Prefer Not To Say')], default='PREFER_NOT_TO_SAY', help_text='User gender identity.', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(default='en', help_text='Preferred user interface locale.', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, help_text='IP address recorded during most recent login.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='locked_until',
            field=models.DateTimeField(blank=True, help_text='Timestamp until which account remains locked.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when password was last changed.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, help_text='User contact phone number in E.164 format.', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_verified',
            field=models.BooleanField(default=False, help_text='Designates whether phone number has been verified.'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_verified_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when phone number was verified.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended'), ('LOCKED', 'Locked')], db_index=True, default='ACTIVE', help_text='User account status.', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(default='SYSTEM', help_text='Preferred UI display theme.', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='UTC', help_text='Preferred user timezone.', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the entity was created.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, help_text='Primary email address for login and system communications.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when email was verified.', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, default='', help_text='User given name.', max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier (UUIDv4) for entity.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this record is active.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether user can access administrative tools.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, default='', help_text='User family name.', max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the entity was last updated.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, help_text='Unique username handle.', max_length=150, unique=True),
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier (UUIDv4) for entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the entity was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entity was last updated.')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when entity was soft-deleted, null if active.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('device_name', models.CharField(blank=True, default='', help_text='Human readable device description or hostname.', max_length=255)),
                ('device_type', models.CharField(choices=[('DESKTOP', 'Desktop'), ('MOBILE', 'Mobile'), ('TABLET', 'Tablet'), ('SMART_TV', 'Smart TV'), ('OTHER', 'Other'), ('UNKNOWN', 'Unknown')], db_index=True, default='UNKNOWN', help_text='Device hardware category.', max_length=50)),
                ('browser', models.CharField(blank=True, default='', help_text='Browser client name and version.', max_length=100)),
                ('os', models.CharField(blank=True, default='', help_text='Operating system name and version.', max_length=100)),
                ('platform', models.CharField(blank=True, default='', help_text='Platform hardware architecture.', max_length=100)),
                ('user_agent', models.TextField(blank=True, default='', help_text='Full HTTP user agent header string.')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Last recorded device IP address.', null=True)),
                ('fingerprint', models.CharField(blank=True, db_index=True, default='', help_text='Unique hardware/browser device fingerprint hash.', max_length=255)),
                ('is_trusted', models.BooleanField(db_index=True, default=False, help_text='Designates whether user explicitly marked device as trusted.')),
                ('last_active', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Timestamp of last activity recorded from device.')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User owner of this device.', on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'device',
                'verbose_name_plural': 'devices',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_device',
            field=models.ForeignKey(blank=True, help_text='Device recorded during most recent login.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_last_login', to='accounts.device'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email', 'status'], name='idx_user_email_status'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['status', 'deleted_at'], name='idx_user_status_deleted'),
        ),
        migrations.AddField(
            model_name='emailverificationtoken',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailverificationtoken',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailverificationtoken',
            name='user',
            field=models.ForeignKey(help_text='User verifying primary email address.', on_delete=django.db.models.deletion.CASCADE, related_name='email_verification_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='device',
            field=models.ForeignKey(blank=True, help_text='Device record associated with event.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_logs', to='accounts.device'),
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User associated with event, if authenticated.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='passwordresettoken',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='passwordresettoken',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='passwordresettoken',
            name='user',
            field=models.ForeignKey(help_text='User requesting password reset.', on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='user',
            field=models.OneToOneField(help_text='User owner of these preferences.', on_delete=django.db.models.deletion.CASCADE, related_name='preference', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(help_text='User owner of this profile.', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersession',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersession',
            name='device',
            field=models.ForeignKey(blank=True, help_text='Associated user device.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='accounts.device'),
        ),
        migrations.AddField(
            model_name='usersession',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersession',
            name='user',
            field=models.ForeignKey(help_text='User owner of this active session.', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['user', 'fingerprint'], name='idx_device_user_fingerprint'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['user', 'last_active'], name='idx_device_user_lastactive'),
        ),
        migrations.AddIndex(
            model_name='emailverificationtoken',
            index=models.Index(fields=['user', 'is_used', 'expires_at'], name='idx_emailtoken_user_used_exp'),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['user', 'event_type', 'timestamp'], name='idx_loginhist_user_evt_time'),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['email_attempted', 'timestamp'], name='idx_loginhist_email_time'),
        ),
        migrations.AddIndex(
            model_name='passwordresettoken',
            index=models.Index(fields=['user', 'is_used', 'expires_at'], name='idx_pwdtoken_user_used_exp'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['country', 'visibility'], name='idx_profile_country_vis'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', 'status'], name='idx_session_user_status'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['status', 'refresh_token_expires_at'], name='idx_session_status_exp'),
        ),
    ]
