services:
  web:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: nexora-engine

    command: >
      gunicorn config.wsgi:application
      --bind 0.0.0.0:8000
      --workers 3
      --timeout 120

    env_file:
      - .env

    volumes:
      - .:/app
      - ../../infrastructure/volumes/static:/app/staticfiles

    ports:
      - "8000:8000"

    networks:
      - nexora-network

networks:
  nexora-network:
    external: true
    name: nexora-infra_nexora-network
