# Generated by Django 5.2.11 on 2026-08-01 09:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_managerassignment_workforceassignment'),
        ('leaves', '0001_initial'),
        ('organizations', '0004_shiftroster_shiftrosterassignment_shiftrotation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalDelegation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier (UUIDv4) for entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the entity was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entity was last updated.')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when entity was soft-deleted, null if active.', null=True)),
                ('start_date', models.DateField(db_index=True, help_text='Delegation effective start date.')),
                ('end_date', models.DateField(db_index=True, help_text='Delegation effective end date.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Active flag for delegation rule.')),
                ('reason', models.TextField(blank=True, help_text='Rationale for delegation.')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('delegatee', models.ForeignKey(help_text='Temporary backup approver receiving authority.', on_delete=django.db.models.deletion.CASCADE, related_name='incoming_delegations', to='employees.employee')),
                ('delegator', models.ForeignKey(help_text='Manager delegating approval authority.', on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_delegations', to='employees.employee')),
                ('organization', models.ForeignKey(help_text='Associated Organization.', on_delete=django.db.models.deletion.CASCADE, related_name='approval_delegations', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'approval delegation',
                'verbose_name_plural': 'approval delegations',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier (UUIDv4) for entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the entity was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entity was last updated.')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when entity was soft-deleted, null if active.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('start_date', models.DateField(db_index=True, help_text='Leave start date.')),
                ('end_date', models.DateField(db_index=True, help_text='Leave end date.')),
                ('total_days', models.DecimalField(decimal_places=2, help_text='Calculated actual working leave days duration.', max_digits=5)),
                ('is_half_day', models.BooleanField(default=False, help_text='Flag indicating half-day leave request.')),
                ('half_day_period', models.CharField(blank=True, choices=[('FIRST_HALF', 'First Half of Working Day'), ('SECOND_HALF', 'Second Half of Working Day')], help_text='Half day session (FIRST_HALF or SECOND_HALF).', max_length=20, null=True)),
                ('reason', models.TextField(help_text='Reason for leave request.')),
                ('attachment_url', models.URLField(blank=True, help_text='URL or path to supporting medical/official document.', max_length=500)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft Request'), ('SUBMITTED', 'Submitted for Approval'), ('PENDING', 'Pending Approver Decision'), ('APPROVED', 'Approved Leave'), ('REJECTED', 'Rejected Leave'), ('CANCELLED', 'Cancelled Leave'), ('WITHDRAWN', 'Withdrawn by Employee'), ('EXPIRED', 'Workflow Expired'), ('RETURNED_FOR_CORRECTION', 'Returned to Employee for Revision')], db_index=True, default='DRAFT', help_text='Current workflow status.', max_length=50)),
                ('current_approval_level', models.CharField(choices=[('LEVEL_1_MANAGER', 'Level 1 Reporting Manager'), ('LEVEL_2_HR', 'Level 2 HR Business Partner'), ('LEVEL_3_ADMIN', 'Level 3 Organization Executive/Admin')], default='LEVEL_1_MANAGER', help_text='Current pending approval level.', max_length=50)),
                ('max_approval_levels', models.PositiveIntegerField(default=1, help_text='Configured approval levels required (1 to 3).')),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection if rejected.')),
                ('cancellation_reason', models.TextField(blank=True, help_text='Reason for cancellation if cancelled.')),
                ('is_emergency', models.BooleanField(default=False, help_text='Emergency leave request flag bypassing standard notice period.')),
                ('is_past_leave', models.BooleanField(default=False, help_text='Past date retroactive leave request flag.')),
                ('approver', models.ForeignKey(blank=True, help_text='Currently assigned decision-making approver.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_leave_approvals', to='employees.employee')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(help_text='Applicant Employee.', on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='employees.employee')),
                ('leave_balance', models.ForeignKey(help_text='Associated LeaveBalance record.', on_delete=django.db.models.deletion.PROTECT, related_name='leave_requests', to='leaves.leavebalance')),
                ('leave_type', models.ForeignKey(help_text='Applied LeaveType.', on_delete=django.db.models.deletion.PROTECT, related_name='leave_requests', to='leaves.leavetype')),
                ('organization', models.ForeignKey(help_text='Associated Organization.', on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='organizations.organization')),
                ('policy', models.ForeignKey(help_text='Governing LeavePolicy.', on_delete=django.db.models.deletion.PROTECT, related_name='leave_requests', to='leaves.leavepolicy')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'leave request',
                'verbose_name_plural': 'leave requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveApprovalStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier (UUIDv4) for entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the entity was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entity was last updated.')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when entity was soft-deleted, null if active.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('level', models.CharField(choices=[('LEVEL_1_MANAGER', 'Level 1 Reporting Manager'), ('LEVEL_2_HR', 'Level 2 HR Business Partner'), ('LEVEL_3_ADMIN', 'Level 3 Organization Executive/Admin')], help_text='Approval level classification.', max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft Request'), ('SUBMITTED', 'Submitted for Approval'), ('PENDING', 'Pending Approver Decision'), ('APPROVED', 'Approved Leave'), ('REJECTED', 'Rejected Leave'), ('CANCELLED', 'Cancelled Leave'), ('WITHDRAWN', 'Withdrawn by Employee'), ('EXPIRED', 'Workflow Expired'), ('RETURNED_FOR_CORRECTION', 'Returned to Employee for Revision')], default='PENDING', help_text='Decision status for this step.', max_length=50)),
                ('comments', models.TextField(blank=True, help_text='Approver comments or rationale.')),
                ('decision_timestamp', models.DateTimeField(blank=True, help_text='Timestamp of decision.', null=True)),
                ('approver', models.ForeignKey(help_text='Approver performing decision.', on_delete=django.db.models.deletion.PROTECT, related_name='approval_decisions', to='employees.employee')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('leave_request', models.ForeignKey(help_text='Parent LeaveRequest.', on_delete=django.db.models.deletion.CASCADE, related_name='approval_steps', to='leaves.leaverequest')),
            ],
            options={
                'verbose_name': 'leave approval step',
                'verbose_name_plural': 'leave approval steps',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequestHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier (UUIDv4) for entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the entity was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entity was last updated.')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when entity was soft-deleted, null if active.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('action', models.CharField(help_text='Action performed (e.g. SUBMITTED, APPROVED, MODIFIED, CANCELLED).', max_length=50)),
                ('modification_type', models.CharField(blank=True, choices=[('DATE_CHANGE', 'Leave Date Range Modified'), ('LEAVE_TYPE_CHANGE', 'Leave Category Modified'), ('REASON_CHANGE', 'Reason / Metadata Modified')], help_text='Modification category if action is MODIFIED.', max_length=50, null=True)),
                ('previous_state', models.JSONField(blank=True, default=dict, help_text='JSON snapshot of request prior to action.')),
                ('new_state', models.JSONField(blank=True, default=dict, help_text='JSON snapshot of request after action.')),
                ('comments', models.TextField(blank=True, help_text='User or system action notes.')),
                ('actor_user_id', models.CharField(blank=True, help_text='User ID of actor.', max_length=100)),
                ('actor_email', models.CharField(blank=True, help_text='Email address of actor.', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('leave_request', models.ForeignKey(help_text='Parent LeaveRequest.', on_delete=django.db.models.deletion.CASCADE, related_name='history', to='leaves.leaverequest')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'leave request history',
                'verbose_name_plural': 'leave request histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['employee', 'status'], name='idx_leavereq_emp_status'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['organization', 'start_date', 'end_date'], name='idx_leavereq_org_dates'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['approver', 'status'], name='idx_leavereq_appr_status'),
        ),
        migrations.AddConstraint(
            model_name='leaveapprovalstep',
            constraint=models.UniqueConstraint(fields=('leave_request', 'level'), name='unique_leaveapprstep_req_level'),
        ),
    ]
