"""Constants and default configuration parameters for the attendance domain."""

# Policy defaults
DEFAULT_GRACE_TIME_MINUTES = 15
DEFAULT_LATE_THRESHOLD_MINUTES = 30
DEFAULT_EARLY_EXIT_THRESHOLD_MINUTES = 30
DEFAULT_MINIMUM_WORKING_HOURS = 4.0
DEFAULT_FULL_DAY_WORKING_HOURS = 8.0
DEFAULT_MAXIMUM_WORKING_HOURS = 12.0
DEFAULT_ATTENDANCE_LOCK_DAYS = 30
