# Generated by Django 5.2.11 on 2026-08-01 08:45

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0003_managerassignment_workforceassignment'),
        ('organizations', '0003_organizationlimit_max_shifts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendancePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier (UUIDv4) for entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the entity was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entity was last updated.')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when entity was soft-deleted, null if active.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('name', models.CharField(help_text='Policy display name (e.g., Standard 9-to-5 Policy).', max_length=255)),
                ('code', models.CharField(db_index=True, help_text='Unique policy code within organization.', max_length=50)),
                ('grace_time_minutes', models.PositiveIntegerField(default=15, help_text='Grace period in minutes before marking late arrival.')),
                ('late_threshold_minutes', models.PositiveIntegerField(default=30, help_text='Threshold in minutes to trigger late status deduction.')),
                ('early_exit_threshold_minutes', models.PositiveIntegerField(default=30, help_text='Threshold in minutes to trigger early exit status.')),
                ('minimum_working_hours', models.DecimalField(decimal_places=2, default=Decimal('4.0'), help_text='Minimum working hours required for half-day credit.', max_digits=4)),
                ('full_day_working_hours', models.DecimalField(decimal_places=2, default=Decimal('8.0'), help_text='Minimum working hours required for full-day credit.', max_digits=4)),
                ('maximum_working_hours', models.DecimalField(decimal_places=2, default=Decimal('12.0'), help_text='Maximum allowable working hours per day.', max_digits=4)),
                ('overtime_allowed', models.BooleanField(default=True, help_text='Flag indicating whether overtime calculation is enabled.')),
                ('half_day_allowed', models.BooleanField(default=True, help_text='Flag indicating whether half-day attendance is permitted.')),
                ('auto_checkout_enabled', models.BooleanField(default=False, help_text='Flag enabling automated checkout at designated time.')),
                ('auto_checkout_time', models.TimeField(blank=True, help_text='Time of day to execute automated system checkout.', null=True)),
                ('approval_required', models.BooleanField(default=True, help_text='Flag indicating whether attendance adjustments require approval.')),
                ('is_default', models.BooleanField(db_index=True, default=False, help_text='Flag indicating default policy for organization.')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='Associated Organization instance.', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_policies', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'attendance policy',
                'verbose_name_plural': 'attendance policies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier (UUIDv4) for entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the entity was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entity was last updated.')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when entity was soft-deleted, null if active.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('allow_future_attendance', models.BooleanField(default=False, help_text='Allow logging attendance for future dates.')),
                ('allow_manual_entry', models.BooleanField(default=True, help_text='Allow manual attendance entry by managers.')),
                ('allow_wfh_request', models.BooleanField(default=True, help_text='Allow work-from-home requests.')),
                ('lock_attendance_days', models.PositiveIntegerField(default=30, help_text='Number of days after which past attendance records are locked.')),
                ('branch', models.ForeignKey(blank=True, help_text='Target Branch (null for organization wide).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_configurations', to='organizations.branch')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, help_text='Target Department (null for branch wide).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_configurations', to='organizations.department')),
                ('organization', models.ForeignKey(help_text='Target Organization.', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_configurations', to='organizations.organization')),
                ('team', models.ForeignKey(blank=True, help_text='Target Team (null for department wide).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_configurations', to='organizations.team')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('default_policy', models.ForeignKey(help_text='Default Attendance Policy applied at this hierarchy level.', on_delete=django.db.models.deletion.PROTECT, related_name='configurations', to='attendance.attendancepolicy')),
            ],
            options={
                'verbose_name': 'attendance configuration',
                'verbose_name_plural': 'attendance configurations',
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier (UUIDv4) for entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the entity was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entity was last updated.')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when entity was soft-deleted, null if active.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('attendance_date', models.DateField(db_index=True, help_text='Target calendar date of attendance.')),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('HALF_DAY', 'Half Day'), ('LATE', 'Late Arrival'), ('EARLY_EXIT', 'Early Departure'), ('WORK_FROM_HOME', 'Work From Home (WFH)'), ('REMOTE', 'Remote Work Location'), ('BUSINESS_TRAVEL', 'Official Business Travel'), ('ON_DUTY', 'On Official Duty'), ('HOLIDAY', 'Public / Company Holiday'), ('WEEKLY_OFF', 'Scheduled Weekly Off'), ('LEAVE', 'Approved Leave'), ('SUSPENDED', 'Employee Suspended'), ('TRAINING', 'Attending Training'), ('MEETING', 'External Client Meeting')], db_index=True, default='PRESENT', help_text='Primary attendance status classification.', max_length=50)),
                ('source', models.CharField(choices=[('WEB', 'Web Portal Interface'), ('MOBILE', 'Mobile Application'), ('BIOMETRIC', 'Biometric Terminal'), ('API', 'REST API Service'), ('IMPORT', 'Bulk File Import'), ('ADMIN_ENTRY', 'Manual Administrative Entry'), ('QR_CODE', 'QR Code Scanner'), ('KIOSK', 'Attendance Kiosk Device')], default='WEB', help_text='Origin source device/method of attendance.', max_length=50)),
                ('work_location', models.CharField(blank=True, help_text='Work location description at time of attendance.', max_length=255)),
                ('approval_status', models.CharField(choices=[('DRAFT', 'Draft Entry'), ('PENDING', 'Pending Manager Review'), ('APPROVED', 'Approved by Manager / HR'), ('REJECTED', 'Rejected')], db_index=True, default='APPROVED', help_text='Manager/HR approval workflow status.', max_length=50)),
                ('working_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated actual net working hours.', max_digits=5)),
                ('break_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total break duration hours.', max_digits=5)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated overtime hours.', max_digits=5)),
                ('is_night_shift', models.BooleanField(default=False, help_text='Flag indicating attendance crosses midnight (night shift).')),
                ('is_locked', models.BooleanField(db_index=True, default=False, help_text='Flag indicating attendance record is locked against modifications.')),
                ('remarks', models.TextField(blank=True, help_text='Notes or exception remarks.')),
                ('branch', models.ForeignKey(help_text='Branch instance at time of attendance.', on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='organizations.branch')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(help_text='Department instance at time of attendance.', on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='organizations.department')),
                ('designation', models.ForeignKey(help_text='Designation instance at time of attendance.', on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='organizations.designation')),
                ('employee', models.ForeignKey(help_text='Employee instance.', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='employees.employee')),
                ('organization', models.ForeignKey(help_text='Organization instance.', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='organizations.organization')),
                ('policy', models.ForeignKey(help_text='Governing Attendance Policy applied.', on_delete=django.db.models.deletion.PROTECT, related_name='records', to='attendance.attendancepolicy')),
                ('shift', models.ForeignKey(blank=True, help_text='Assigned Shift template.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='organizations.shift')),
                ('team', models.ForeignKey(blank=True, help_text='Team unit instance.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='organizations.team')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'attendance record',
                'verbose_name_plural': 'attendance records',
                'ordering': ['-attendance_date', 'employee'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier (UUIDv4) for entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the entity was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entity was last updated.')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when entity was soft-deleted, null if active.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('event_type', models.CharField(db_index=True, help_text='Type of audit event (e.g., CREATED, LOCKED, CORRECTED).', max_length=50)),
                ('actor_user_id', models.CharField(blank=True, help_text='User ID of actor executing mutation.', max_length=100)),
                ('actor_email', models.CharField(blank=True, help_text='Email address of actor.', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Client IP address.', null=True)),
                ('request_id', models.CharField(blank=True, help_text='Correlation request ID.', max_length=100)),
                ('previous_state', models.JSONField(blank=True, default=dict, help_text='Previous state JSON snapshot.')),
                ('new_state', models.JSONField(blank=True, default=dict, help_text='New state JSON snapshot.')),
                ('reason', models.TextField(blank=True, help_text='Rationale for event change.')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Event creation timestamp.')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('attendance_record', models.ForeignKey(help_text='Associated AttendanceRecord.', on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='attendance.attendancerecord')),
            ],
            options={
                'verbose_name': 'attendance audit event',
                'verbose_name_plural': 'attendance audit events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier (UUIDv4) for entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the entity was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entity was last updated.')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when entity was soft-deleted, null if active.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('check_in', models.DateTimeField(help_text='Check-in timestamp.')),
                ('check_out', models.DateTimeField(blank=True, help_text='Check-out timestamp.', null=True)),
                ('session_duration_minutes', models.PositiveIntegerField(default=0, help_text='Total session duration in minutes.')),
                ('is_auto_checked_out', models.BooleanField(default=False, help_text='Flag indicating system auto checkout.')),
                ('attendance_record', models.ForeignKey(help_text='Parent daily AttendanceRecord.', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='attendance.attendancerecord')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'attendance session',
                'verbose_name_plural': 'attendance sessions',
                'ordering': ['check_in'],
            },
        ),
        migrations.AddIndex(
            model_name='attendancepolicy',
            index=models.Index(fields=['organization', 'is_default'], name='idx_attpolicy_org_default'),
        ),
        migrations.AddConstraint(
            model_name='attendancepolicy',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_attpolicy_org_code'),
        ),
        migrations.AddConstraint(
            model_name='attendanceconfiguration',
            constraint=models.UniqueConstraint(fields=('organization', 'branch', 'department', 'team'), name='unique_attconfig_hierarchy'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['employee', 'attendance_date'], name='idx_attrec_emp_date'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['organization', 'attendance_date', 'status'], name='idx_attrec_org_date_status'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(fields=('employee', 'attendance_date'), name='unique_attrecord_emp_date'),
        ),
        migrations.AddIndex(
            model_name='attendanceevent',
            index=models.Index(fields=['attendance_record', 'event_type'], name='idx_attevent_rec_type'),
        ),
    ]
