# Generated by Django 5.2.11 on 2026-08-01 08:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('employees', '0003_managerassignment_workforceassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceBreak',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier (UUIDv4) for entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the entity was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entity was last updated.')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when entity was soft-deleted, null if active.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('break_type', models.CharField(choices=[('LUNCH', 'Lunch Break'), ('TEA', 'Tea / Coffee Break'), ('PERSONAL', 'Personal Work Break'), ('OFFICIAL', 'Official Movement Break')], default='LUNCH', help_text='Category classification of break.', max_length=50)),
                ('start_time', models.DateTimeField(help_text='Break start timestamp.')),
                ('end_time', models.DateTimeField(blank=True, help_text='Break end timestamp.', null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=0, help_text='Total break duration in minutes.')),
                ('is_paid', models.BooleanField(default=False, help_text='Flag indicating whether break duration counts toward working hours.')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(help_text='Associated parent AttendanceSession.', on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='attendance.attendancesession')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'attendance break',
                'verbose_name_plural': 'attendance breaks',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceCorrectionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier (UUIDv4) for entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the entity was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entity was last updated.')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when entity was soft-deleted, null if active.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('requested_check_in', models.DateTimeField(blank=True, help_text='Proposed corrected check-in timestamp.', null=True)),
                ('requested_check_out', models.DateTimeField(blank=True, help_text='Proposed corrected check-out timestamp.', null=True)),
                ('requested_status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('HALF_DAY', 'Half Day'), ('LATE', 'Late Arrival'), ('EARLY_EXIT', 'Early Departure'), ('WORK_FROM_HOME', 'Work From Home (WFH)'), ('REMOTE', 'Remote Work Location'), ('BUSINESS_TRAVEL', 'Official Business Travel'), ('ON_DUTY', 'On Official Duty'), ('HOLIDAY', 'Public / Company Holiday'), ('WEEKLY_OFF', 'Scheduled Weekly Off'), ('LEAVE', 'Approved Leave'), ('SUSPENDED', 'Employee Suspended'), ('TRAINING', 'Attending Training'), ('MEETING', 'External Client Meeting')], default='PRESENT', help_text='Proposed corrected status.', max_length=50)),
                ('reason', models.TextField(help_text='Operational rationale for attendance adjustment.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved by Manager / HR'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', help_text='Workflow approval status.', max_length=50)),
                ('processed_by_id', models.CharField(blank=True, help_text='User ID of manager/HR approving/rejecting request.', max_length=100)),
                ('processed_at', models.DateTimeField(blank=True, help_text='Approval timestamp.', null=True)),
                ('attendance_record', models.ForeignKey(help_text='Target AttendanceRecord to correct.', on_delete=django.db.models.deletion.CASCADE, related_name='correction_requests', to='attendance.attendancerecord')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(help_text='Employee submitting the correction request.', on_delete=django.db.models.deletion.CASCADE, related_name='submitted_attendance_corrections', to='employees.employee')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'attendance correction request',
                'verbose_name_plural': 'attendance correction requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['attendance_record', 'status'], name='idx_attcorr_rec_status')],
            },
        ),
    ]
