# Generated by Django 5.2.11 on 2026-08-01 10:07

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_managerassignment_workforceassignment'),
        ('organizations', '0004_shiftroster_shiftrosterassignment_shiftrotation_and_more'),
        ('payroll', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier (UUIDv4) for entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the entity was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entity was last updated.')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when entity was soft-deleted, null if active.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('name', models.CharField(help_text='Human-readable run name.', max_length=200)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft Payroll Run'), ('CALCULATED', 'Calculated Salaries'), ('VALIDATED', 'Validated Calculation'), ('APPROVED', 'Approved by Authorized Personnel'), ('FINALIZED', 'Finalized & Locked'), ('LOCKED', 'Period Locked'), ('REOPENED', 'Reopened for Corrections'), ('ROLLED_BACK', 'Rolled Back Run')], default='DRAFT', help_text='Current processing status.', max_length=50)),
                ('total_employees', models.PositiveIntegerField(default=0, help_text='Total employees processed.')),
                ('total_gross', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Aggregate gross salary.', max_digits=16)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Aggregate deductions.', max_digits=16)),
                ('total_employer_contributions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Aggregate employer statutory contributions.', max_digits=16)),
                ('total_net', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Aggregate net salary.', max_digits=16)),
                ('calculated_at', models.DateTimeField(blank=True, help_text='Timestamp when calculation completed.', null=True)),
                ('finalized_at', models.DateTimeField(blank=True, help_text='Timestamp when run finalized.', null=True)),
                ('is_locked', models.BooleanField(default=False, help_text='Whether the run is locked against modifications.')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='Associated organization.', on_delete=django.db.models.deletion.PROTECT, related_name='payroll_runs', to='organizations.organization')),
                ('payroll_cycle', models.ForeignKey(help_text='Associated payroll cycle.', on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='payroll.payrollcycle')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payroll Run',
                'verbose_name_plural': 'Payroll Runs',
            },
        ),
        migrations.CreateModel(
            name='PayrollLock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier (UUIDv4) for entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the entity was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entity was last updated.')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when entity was soft-deleted, null if active.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('lock_start_date', models.DateField(help_text='Lock period start date.')),
                ('lock_end_date', models.DateField(help_text='Lock period end date.')),
                ('attendance_locked', models.BooleanField(default=True, help_text='Attendance data is locked.')),
                ('leave_locked', models.BooleanField(default=True, help_text='Leave data is locked.')),
                ('payroll_locked', models.BooleanField(default=True, help_text='Payroll master data is locked.')),
                ('locked_by_user_id', models.CharField(blank=True, help_text='User ID who initiated the lock.', max_length=100)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='Associated organization.', on_delete=django.db.models.deletion.PROTECT, related_name='payroll_locks', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('payroll_run', models.ForeignKey(blank=True, help_text='Associated payroll run.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locks', to='payroll.payrollrun')),
            ],
            options={
                'verbose_name': 'Payroll Lock',
                'verbose_name_plural': 'Payroll Locks',
            },
        ),
        migrations.CreateModel(
            name='PayrollItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier (UUIDv4) for entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the entity was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entity was last updated.')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when entity was soft-deleted, null if active.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Calculation'), ('CALCULATED', 'Salary Calculated Successfully'), ('ERROR', 'Calculation Error Encountered'), ('APPROVED', 'Salary Approved'), ('PAID', 'Salary Disbursed')], default='PENDING', help_text='Calculation status.', max_length=50)),
                ('total_working_days', models.PositiveIntegerField(default=0, help_text='Total working days in period.')),
                ('days_present', models.PositiveIntegerField(default=0, help_text='Days present (from attendance).')),
                ('days_absent', models.PositiveIntegerField(default=0, help_text='Days absent.')),
                ('paid_leave_days', models.PositiveIntegerField(default=0, help_text='Paid leave days consumed.')),
                ('unpaid_leave_days', models.PositiveIntegerField(default=0, help_text='Unpaid / LOP leave days deducted.')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Overtime hours worked.', max_digits=8)),
                ('earned_basic', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Prorated earned basic salary.', max_digits=12)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of all earning components.', max_digits=14)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of all deduction components.', max_digits=14)),
                ('employer_pf', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Employer PF contribution.', max_digits=12)),
                ('employer_esi', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Employer ESI contribution.', max_digits=12)),
                ('gross_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Gross salary before deductions.', max_digits=14)),
                ('net_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Net take-home salary after deductions.', max_digits=14)),
                ('error_message', models.TextField(blank=True, help_text='Error details if calculation failed.')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(help_text='Associated employee.', on_delete=django.db.models.deletion.PROTECT, related_name='payroll_items', to='employees.employee')),
                ('salary_structure', models.ForeignKey(help_text='Salary structure used for calculation.', on_delete=django.db.models.deletion.PROTECT, related_name='payroll_items', to='payroll.employeesalarystructure')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('payroll_run', models.ForeignKey(help_text='Parent payroll run.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payroll.payrollrun')),
            ],
            options={
                'verbose_name': 'Payroll Item',
                'verbose_name_plural': 'Payroll Items',
            },
        ),
        migrations.CreateModel(
            name='PayrollApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier (UUIDv4) for entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the entity was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entity was last updated.')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when entity was soft-deleted, null if active.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('level', models.CharField(choices=[('LEVEL_1_FINANCE', 'Level 1 - Finance Review'), ('LEVEL_2_HR', 'Level 2 - HR Authorization'), ('LEVEL_3_MANAGEMENT', 'Level 3 - Executive Management Signoff')], help_text='Approval level.', max_length=50)),
                ('decision', models.CharField(default='APPROVED', help_text='Approval decision.', max_length=20)),
                ('comments', models.TextField(blank=True, help_text='Approval comments or notes.')),
                ('approver', models.ForeignKey(help_text='Approving employee.', on_delete=django.db.models.deletion.PROTECT, related_name='payroll_approvals_given', to='employees.employee')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('payroll_run', models.ForeignKey(help_text='Associated payroll run.', on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='payroll.payrollrun')),
            ],
            options={
                'verbose_name': 'Payroll Approval',
                'verbose_name_plural': 'Payroll Approvals',
            },
        ),
        migrations.CreateModel(
            name='PayrollItemComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier (UUIDv4) for entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the entity was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entity was last updated.')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when entity was soft-deleted, null if active.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated amount for this component.', max_digits=14)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('payroll_item', models.ForeignKey(help_text='Parent payroll item.', on_delete=django.db.models.deletion.CASCADE, related_name='component_details', to='payroll.payrollitem')),
                ('salary_component', models.ForeignKey(help_text='Linked salary component.', on_delete=django.db.models.deletion.PROTECT, related_name='payroll_item_details', to='payroll.salarycomponent')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payroll Item Component',
                'verbose_name_plural': 'Payroll Item Components',
                'unique_together': {('payroll_item', 'salary_component')},
            },
        ),
        migrations.AddIndex(
            model_name='payrollrun',
            index=models.Index(fields=['organization', 'status'], name='idx_payrun_org_status'),
        ),
        migrations.AddIndex(
            model_name='payrollrun',
            index=models.Index(fields=['payroll_cycle', 'status'], name='idx_payrun_cycle_status'),
        ),
        migrations.AddIndex(
            model_name='payrollitem',
            index=models.Index(fields=['payroll_run', 'status'], name='idx_payitem_run_status'),
        ),
        migrations.AlterUniqueTogether(
            name='payrollitem',
            unique_together={('payroll_run', 'employee')},
        ),
        migrations.AlterUniqueTogether(
            name='payrollapproval',
            unique_together={('payroll_run', 'level')},
        ),
    ]
