# Generated by Django 5.2.11 on 2026-08-01 10:15

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_managerassignment_workforceassignment'),
        ('organizations', '0004_shiftroster_shiftrosterassignment_shiftrotation_and_more'),
        ('payroll', '0002_payrollrun_payrolllock_payrollitem_payrollapproval_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier (UUIDv4) for entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the entity was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entity was last updated.')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when entity was soft-deleted, null if active.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('payslip_number', models.CharField(help_text='Unique payslip serial/number per organization.', max_length=100)),
                ('payslip_type', models.CharField(choices=[('MONTHLY', 'Standard Monthly Payslip'), ('OFF_CYCLE', 'Off-Cycle Salary Disbursement'), ('CORRECTION', 'Correction / Adjustment Payslip'), ('FINAL_SETTLEMENT', 'Full & Final Settlement Payslip')], default='MONTHLY', help_text='Classification of payslip (Monthly, Off-Cycle, Correction).', max_length=50)),
                ('status', models.CharField(choices=[('GENERATED', 'Generated Payslip'), ('PUBLISHED', 'Published to ESS Portal'), ('REVOKED', 'Revoked Payslip'), ('ARCHIVED', 'Archived Payslip')], default='GENERATED', help_text='Publication and access status.', max_length=50)),
                ('version', models.PositiveIntegerField(default=1, help_text='Payslip version number (increments on correction/regeneration).')),
                ('issue_date', models.DateField(help_text='Official date of payslip issue.')),
                ('gross_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Gross salary amount.', max_digits=14)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total deductions amount.', max_digits=14)),
                ('net_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Net take-home salary.', max_digits=14)),
                ('download_token', models.CharField(blank=True, help_text='Secure download access token for ESS portal.', max_length=128)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(help_text='Associated employee.', on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='employees.employee')),
                ('organization', models.ForeignKey(help_text='Associated organization.', on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='organizations.organization')),
                ('payroll_item', models.ForeignKey(help_text='Associated calculated payroll item.', on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='payroll.payrollitem')),
                ('payroll_run', models.ForeignKey(help_text='Associated finalized payroll run.', on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='payroll.payrollrun')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payslip',
                'verbose_name_plural': 'Payslips',
            },
        ),
        migrations.CreateModel(
            name='PayslipComponentDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier (UUIDv4) for entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the entity was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entity was last updated.')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when entity was soft-deleted, null if active.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('component_name', models.CharField(help_text='Name of salary component.', max_length=150)),
                ('component_code', models.CharField(help_text='Code of salary component.', max_length=50)),
                ('component_type', models.CharField(choices=[('EARNING', 'Earning Component'), ('DEDUCTION', 'Deduction Component'), ('STATUTORY', 'Statutory Component'), ('REIMBURSEMENT', 'Reimbursement Component')], default='EARNING', help_text='Component classification.', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Line item component amount.', max_digits=14)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('payslip', models.ForeignKey(help_text='Parent payslip.', on_delete=django.db.models.deletion.CASCADE, related_name='components', to='payroll.payslip')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payslip Component Detail',
                'verbose_name_plural': 'Payslip Component Details',
            },
        ),
        migrations.CreateModel(
            name='RetroactiveAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier (UUIDv4) for entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the entity was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entity was last updated.')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when entity was soft-deleted, null if active.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('category', models.CharField(choices=[('ARREARS', 'Salary Arrears Addition'), ('RECOVERY', 'Salary Recovery Deduction'), ('SALARY_DIFFERENCE', 'Salary Revision Difference'), ('ATTENDANCE_CORRECTION', 'Attendance Regularization Impact'), ('LEAVE_ADJUSTMENT', 'Unpaid Leave LOP Adjustment'), ('MANUAL', 'Manual Ad-Hoc Adjustment')], default='ARREARS', help_text='Category of adjustment.', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Adjustment amount (positive for arrears/earnings, negative for recovery).', max_digits=14)),
                ('effective_date', models.DateField(help_text='Effective historical date for calculation.')),
                ('reason', models.TextField(help_text='Explanation or justification for retroactive adjustment.')),
                ('is_processed', models.BooleanField(default=False, help_text='Whether adjustment has been consumed in a payroll run.')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(help_text='Associated employee.', on_delete=django.db.models.deletion.PROTECT, related_name='retroactive_adjustments', to='employees.employee')),
                ('organization', models.ForeignKey(help_text='Associated organization.', on_delete=django.db.models.deletion.PROTECT, related_name='retroactive_adjustments', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Retroactive Adjustment',
                'verbose_name_plural': 'Retroactive Adjustments',
            },
        ),
        migrations.CreateModel(
            name='SalaryDistribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier (UUIDv4) for entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the entity was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entity was last updated.')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when entity was soft-deleted, null if active.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('method', models.CharField(choices=[('BANK_TRANSFER', 'Direct Bank Wire Transfer'), ('CASH', 'Cash Payment'), ('CHEQUE', 'Bank Cheque Disbursement'), ('WALLET', 'Digital Wallet Transfer'), ('UPI', 'Unified Payments Interface (UPI)')], default='BANK_TRANSFER', help_text='Payment disbursement method.', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Disbursement'), ('SCHEDULED', 'Scheduled for Bank Batch'), ('COMPLETED', 'Disbursement Completed Successfully'), ('FAILED', 'Disbursement Transfer Failed'), ('CANCELLED', 'Disbursement Cancelled')], default='PENDING', help_text='Disbursement status.', max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total disbursement amount.', max_digits=16)),
                ('scheduled_date', models.DateField(help_text='Scheduled disbursement date.')),
                ('completed_date', models.DateField(blank=True, help_text='Actual date disbursement completed.', null=True)),
                ('failure_reason', models.TextField(blank=True, help_text='Reason if disbursement batch failed.')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='Associated organization.', on_delete=django.db.models.deletion.PROTECT, related_name='salary_distributions', to='organizations.organization')),
                ('payroll_run', models.ForeignKey(help_text='Associated finalized payroll run.', on_delete=django.db.models.deletion.PROTECT, related_name='distributions', to='payroll.payrollrun')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Salary Distribution',
                'verbose_name_plural': 'Salary Distributions',
            },
        ),
        migrations.CreateModel(
            name='CompensationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier (UUIDv4) for entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the entity was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entity was last updated.')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when entity was soft-deleted, null if active.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('annual_ctc', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Annual CTC snapshot.', max_digits=14)),
                ('monthly_basic', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monthly basic snapshot.', max_digits=12)),
                ('effective_date', models.DateField(help_text='Effective date of compensation change.')),
                ('revision_reason', models.CharField(blank=True, help_text='Reason for compensation change.', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(help_text='Associated employee.', on_delete=django.db.models.deletion.PROTECT, related_name='compensation_histories', to='employees.employee')),
                ('organization', models.ForeignKey(help_text='Associated organization.', on_delete=django.db.models.deletion.PROTECT, related_name='compensation_histories', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compensation History',
                'verbose_name_plural': 'Compensation Histories',
                'indexes': [models.Index(fields=['employee', 'effective_date'], name='idx_comphist_emp_date')],
            },
        ),
        migrations.AddIndex(
            model_name='payslip',
            index=models.Index(fields=['employee', 'issue_date'], name='idx_payslip_emp_date'),
        ),
        migrations.AddIndex(
            model_name='payslip',
            index=models.Index(fields=['payroll_run', 'status'], name='idx_payslip_run_status'),
        ),
        migrations.AddIndex(
            model_name='payslip',
            index=models.Index(fields=['download_token'], name='idx_payslip_token'),
        ),
        migrations.AlterUniqueTogether(
            name='payslip',
            unique_together={('organization', 'payslip_number')},
        ),
        migrations.AddIndex(
            model_name='retroactiveadjustment',
            index=models.Index(fields=['employee', 'is_processed'], name='idx_retro_emp_proc'),
        ),
        migrations.AddIndex(
            model_name='salarydistribution',
            index=models.Index(fields=['payroll_run', 'status'], name='idx_dist_run_status'),
        ),
    ]
