# Generated by Django 5.2.11 on 2026-08-01 10:21

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_managerassignment_workforceassignment'),
        ('organizations', '0004_shiftroster_shiftrosterassignment_shiftrotation_and_more'),
        ('payroll', '0003_payslip_payslipcomponentdetail_retroactiveadjustment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier (UUIDv4) for entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the entity was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entity was last updated.')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when entity was soft-deleted, null if active.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('report_type', models.CharField(choices=[('TAX_SUMMARY', 'Tax Deduction & Slab Summary Report'), ('CONTRIBUTION_SUMMARY', 'Statutory Contribution Breakdown Report'), ('PAYROLL_COMPLIANCE', 'Payroll Run Statutory Compliance Check'), ('ORG_COMPLIANCE', 'Organization Overall Statutory Audit'), ('AUDIT_REPORT', 'Payroll Lock & Adjustment Audit Trail')], default='TAX_SUMMARY', help_text='Classification of compliance report.', max_length=50)),
                ('title', models.CharField(help_text='Human-readable report title.', max_length=200)),
                ('start_date', models.DateField(help_text='Reporting period start date.')),
                ('end_date', models.DateField(help_text='Reporting period end date.')),
                ('summary_json', models.JSONField(default=dict, help_text='Structured report aggregation metrics.')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='Associated organization.', on_delete=django.db.models.deletion.PROTECT, related_name='compliance_reports', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compliance Report',
                'verbose_name_plural': 'Compliance Reports',
            },
        ),
        migrations.CreateModel(
            name='GovernmentFilingRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier (UUIDv4) for entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the entity was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entity was last updated.')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when entity was soft-deleted, null if active.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('filing_type', models.CharField(choices=[('MONTHLY_TAX_RETURN', 'Monthly Tax Deduction Return'), ('PF_ECR_FILING', 'Provident Fund Electronic Challan Return'), ('ESI_RETURNS', 'Employee State Insurance Return'), ('ANNUAL_TAX_CERTIFICATE', 'Annual Employee Tax Statement (Form 16/W2)')], default='MONTHLY_TAX_RETURN', help_text='Type of statutory filing.', max_length=50)),
                ('period_name', models.CharField(help_text='Filing period identifier (e.g. 2026-Q3, 2026-08).', max_length=50)),
                ('status', models.CharField(choices=[('COMPLIANT', 'Fully Compliant'), ('NON_COMPLIANT', 'Non-Compliant / Errors Found'), ('FLAGGED', 'Flagged for HR Review'), ('OVERRIDDEN', 'Compliance Exception Overridden')], default='COMPLIANT', help_text='Current status of filing.', max_length=50)),
                ('total_tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Aggregate tax amount in filing.', max_digits=16)),
                ('total_contribution_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Aggregate contribution amount in filing.', max_digits=16)),
                ('filing_reference_number', models.CharField(blank=True, help_text='Official government acknowledgment/reference ID.', max_length=100)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='Associated organization.', on_delete=django.db.models.deletion.PROTECT, related_name='government_filings', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Government Filing Record',
                'verbose_name_plural': 'Government Filing Records',
            },
        ),
        migrations.CreateModel(
            name='ComplianceException',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier (UUIDv4) for entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the entity was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entity was last updated.')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when entity was soft-deleted, null if active.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('severity', models.CharField(choices=[('INFO', 'Informational Advisory'), ('WARNING', 'Non-Blocking Advisory Warning'), ('ERROR', 'Blocking Compliance Error'), ('CRITICAL', 'Critical Statutory Violation')], default='WARNING', help_text='Severity classification.', max_length=50)),
                ('rule_code', models.CharField(help_text='Violated statutory rule code.', max_length=50)),
                ('description', models.TextField(help_text='Detailed description of compliance exception.')),
                ('is_overridden', models.BooleanField(default=False, help_text='Whether exception was manually overridden by an authorized user.')),
                ('overridden_by_user_id', models.CharField(blank=True, help_text='User ID who performed manual override.', max_length=100)),
                ('override_reason', models.TextField(blank=True, help_text='Justification for manual override.')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, help_text='Associated employee if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_exceptions', to='employees.employee')),
                ('organization', models.ForeignKey(help_text='Associated organization.', on_delete=django.db.models.deletion.PROTECT, related_name='compliance_exceptions', to='organizations.organization')),
                ('payroll_run', models.ForeignKey(blank=True, help_text='Associated payroll run.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compliance_exceptions', to='payroll.payrollrun')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compliance Exception',
                'verbose_name_plural': 'Compliance Exceptions',
                'indexes': [models.Index(fields=['payroll_run', 'severity'], name='idx_compexcep_run_sev')],
            },
        ),
        migrations.CreateModel(
            name='ComplianceRuleConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier (UUIDv4) for entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the entity was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entity was last updated.')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when entity was soft-deleted, null if active.', null=True)),
                ('country_code', models.CharField(default='IN', help_text='ISO 2-letter country code (e.g. IN, US, UK).', max_length=10)),
                ('state_code', models.CharField(blank=True, help_text='State or regional jurisdiction code.', max_length=50)),
                ('rule_code', models.CharField(help_text='Unique statutory rule identifier code.', max_length=50)),
                ('name', models.CharField(help_text='Human-readable rule name.', max_length=150)),
                ('min_wage_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Statutory minimum wage threshold.', max_digits=12)),
                ('max_contribution_cap', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Statutory contribution ceiling cap.', max_digits=14)),
                ('effective_date', models.DateField(help_text='Effective start date for rule application.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether rule configuration is active.')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='Associated organization.', on_delete=django.db.models.deletion.PROTECT, related_name='compliance_rule_configs', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compliance Rule Config',
                'verbose_name_plural': 'Compliance Rule Configs',
                'unique_together': {('organization', 'country_code', 'state_code', 'rule_code')},
            },
        ),
    ]
