# Generated by Django 5.2.11 on 2026-08-01 10:26

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_shiftroster_shiftrosterassignment_shiftrotation_and_more'),
        ('payroll', '0004_compliancereport_governmentfilingrecord_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollExecutiveDashboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier (UUIDv4) for entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the entity was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entity was last updated.')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when entity was soft-deleted, null if active.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('dashboard_type', models.CharField(choices=[('CEO', 'CEO Executive Financial Dashboard'), ('HR', 'HR Compensation & Headcount Dashboard'), ('FINANCE', 'Finance Tax & Disbursement Dashboard'), ('PAYROLL', 'Payroll Run Operations Dashboard'), ('ORGANIZATION', 'Organization-Wide Payroll Summary'), ('BRANCH', 'Branch Location Cost Dashboard'), ('DEPARTMENT', 'Departmental Cost Center Dashboard')], default='CEO', help_text='Target executive view type.', max_length=50)),
                ('metrics_json', models.JSONField(default=dict, help_text='Structured metric dictionary tailored for frontend dashboards.')),
                ('refreshed_at', models.DateTimeField(auto_now=True, help_text='Timestamp when metrics were last calculated.')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='Associated organization.', on_delete=django.db.models.deletion.PROTECT, related_name='executive_dashboards', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payroll Executive Dashboard',
                'verbose_name_plural': 'Payroll Executive Dashboards',
            },
        ),
        migrations.CreateModel(
            name='PayrollAnalyticsSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier (UUIDv4) for entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the entity was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entity was last updated.')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when entity was soft-deleted, null if active.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('period_name', models.CharField(help_text='Period designation (e.g. 2026-08, 2026-Q3, 2026).', max_length=50)),
                ('granularity', models.CharField(choices=[('DAILY', 'Daily Metrics'), ('MONTHLY', 'Monthly Metrics'), ('QUARTERLY', 'Quarterly Metrics'), ('YEARLY', 'Yearly Metrics')], default='MONTHLY', help_text='Temporal granularity.', max_length=50)),
                ('total_employees', models.PositiveIntegerField(default=0, help_text='Headcount in snapshot.')),
                ('total_gross', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total gross salary.', max_digits=16)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total deductions.', max_digits=16)),
                ('total_employer_contributions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total employer statutory contributions.', max_digits=16)),
                ('total_net', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total net salary disbursement.', max_digits=16)),
                ('average_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Mean employee salary.', max_digits=14)),
                ('median_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Median employee salary.', max_digits=14)),
                ('overtime_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total overtime expenditure.', max_digits=14)),
                ('branch', models.ForeignKey(blank=True, help_text='Associated branch filter.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_analytics_snapshots', to='organizations.branch')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, help_text='Associated department filter.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_analytics_snapshots', to='organizations.department')),
                ('organization', models.ForeignKey(help_text='Associated organization.', on_delete=django.db.models.deletion.PROTECT, related_name='payroll_analytics_snapshots', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payroll Analytics Snapshot',
                'verbose_name_plural': 'Payroll Analytics Snapshots',
                'indexes': [models.Index(fields=['organization', 'period_name'], name='idx_payanal_org_period')],
            },
        ),
        migrations.CreateModel(
            name='WorkforceCostIntelligence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier (UUIDv4) for entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the entity was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entity was last updated.')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when entity was soft-deleted, null if active.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('period_name', models.CharField(help_text='Period identifier.', max_length=50)),
                ('headcount', models.PositiveIntegerField(default=0, help_text='Employee count in cost group.')),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total workforce cost (gross + employer statutory).', max_digits=16)),
                ('cost_per_employee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Average cost per employee.', max_digits=14)),
                ('branch', models.ForeignKey(blank=True, help_text='Branch location cost center.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost_metrics', to='organizations.branch')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, help_text='Department cost center.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost_metrics', to='organizations.department')),
                ('designation', models.ForeignKey(blank=True, help_text='Designation cost tier.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost_metrics', to='organizations.designation')),
                ('organization', models.ForeignKey(help_text='Associated organization.', on_delete=django.db.models.deletion.PROTECT, related_name='workforce_cost_metrics', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workforce Cost Intelligence',
                'verbose_name_plural': 'Workforce Cost Intelligence Metrics',
                'indexes': [models.Index(fields=['organization', 'period_name'], name='idx_costintel_org_period')],
            },
        ),
    ]
