# Generated by Django 5.2.11 on 2026-08-01 08:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employment_status',
            field=models.CharField(choices=[('CANDIDATE', 'Candidate'), ('OFFER_RELEASED', 'Offer Released'), ('JOINED', 'Joined'), ('PROBATION', 'Probation'), ('CONFIRMED', 'Confirmed'), ('ACTIVE', 'Active'), ('TRANSFERRED', 'Transferred'), ('PROMOTED', 'Promoted'), ('ON_LEAVE', 'On Leave'), ('SUSPENDED', 'Suspended'), ('RESIGNED', 'Resigned'), ('NOTICE_PERIOD', 'Notice Period'), ('EXITED', 'Exited'), ('ARCHIVED', 'Archived'), ('TERMINATED', 'Terminated')], default='PROBATION', help_text='Current lifecycle status of employment.', max_length=50),
        ),
        migrations.CreateModel(
            name='EmployeeResignation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier (UUIDv4) for entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the entity was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entity was last updated.')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when entity was soft-deleted, null if active.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('resignation_date', models.DateField(help_text='Date resignation request was formally submitted.')),
                ('notice_period_days', models.PositiveIntegerField(default=30, help_text='Required notice period duration in days.')),
                ('requested_exit_date', models.DateField(help_text='Employee requested last working day.')),
                ('approved_exit_date', models.DateField(blank=True, help_text='HR/Manager approved last working day.', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], db_index=True, default='PENDING', help_text='Resignation workflow state.', max_length=50)),
                ('reason', models.TextField(blank=True, help_text='Stated reason for resignation.')),
                ('comments', models.TextField(blank=True, help_text='Manager/HR approval or rejection comments.')),
                ('processed_by_id', models.CharField(blank=True, help_text='User UUID of approving/rejecting manager or HR officer.', max_length=100)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(help_text='Associated employee record.', on_delete=django.db.models.deletion.CASCADE, related_name='resignations', to='employees.employee')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'employee resignation',
                'verbose_name_plural': 'employee resignations',
                'ordering': ['-resignation_date'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier (UUIDv4) for entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the entity was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entity was last updated.')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when entity was soft-deleted, null if active.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('event_type', models.CharField(db_index=True, help_text='Category identifier of the audit event.', max_length=100)),
                ('user_id', models.CharField(blank=True, help_text='UUID of the initiating user.', max_length=100)),
                ('user_email', models.CharField(blank=True, help_text='Email address of the initiating user.', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Client IP address.', null=True)),
                ('request_id', models.CharField(blank=True, help_text='Correlation request ID.', max_length=100)),
                ('previous_state', models.JSONField(blank=True, default=dict, help_text='Previous state values snapshot.')),
                ('new_state', models.JSONField(blank=True, default=dict, help_text='New state values snapshot.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context metadata.')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Event creation timestamp.')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(help_text='Associated employee instance.', on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='employees.employee')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'employee audit event',
                'verbose_name_plural': 'employee audit events',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['employee', 'event_type'], name='idx_empaudit_emp_event'), models.Index(fields=['employee', 'timestamp'], name='idx_empaudit_emp_time')],
            },
        ),
    ]
