# Generated by Django 5.2.11 on 2026-08-01 08:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_employment_status_employeeresignation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier (UUIDv4) for entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the entity was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entity was last updated.')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when entity was soft-deleted, null if active.', null=True)),
                ('manager_type', models.CharField(choices=[('PRIMARY', 'Primary Reporting Manager'), ('SECONDARY', 'Secondary Reporting Manager'), ('FUNCTIONAL', 'Functional Manager'), ('HR', 'HR Manager'), ('PROJECT', 'Project Manager'), ('MENTOR', 'Mentor / Advisor')], db_index=True, default='PRIMARY', help_text='Role category of manager assignment.', max_length=50)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Flag indicating active assignment.')),
                ('effective_date', models.DateField(help_text='Effective start date of manager assignment.')),
                ('end_date', models.DateField(blank=True, help_text='End date of manager assignment (null if currently active).', null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(help_text='Subordinate employee instance.', on_delete=django.db.models.deletion.CASCADE, related_name='manager_assignments', to='employees.employee')),
                ('manager', models.ForeignKey(help_text='Assigned manager employee instance.', on_delete=django.db.models.deletion.PROTECT, related_name='subordinate_assignments', to='employees.employee')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'manager assignment',
                'verbose_name_plural': 'manager assignments',
                'ordering': ['-effective_date'],
                'indexes': [models.Index(fields=['employee', 'manager_type', 'is_active'], name='idx_mgrassign_emp_type')],
            },
        ),
        migrations.CreateModel(
            name='WorkforceAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier (UUIDv4) for entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the entity was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entity was last updated.')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when entity was soft-deleted, null if active.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('assignment_type', models.CharField(choices=[('SHIFT', 'Shift Template Assignment'), ('WORK_LOCATION', 'Work Location Assignment'), ('TEAM', 'Team Unit Assignment'), ('DEPARTMENT', 'Department Unit Assignment'), ('BRANCH', 'Branch Unit Assignment'), ('MANAGER', 'Reporting Manager Assignment')], db_index=True, help_text='Movement/Assignment category.', max_length=50)),
                ('effective_date', models.DateField(db_index=True, help_text='Effective start date.')),
                ('end_date', models.DateField(blank=True, help_text='Effective end date (null if current active).', null=True)),
                ('is_temporary', models.BooleanField(default=False, help_text='Flag indicating temporary assignment.')),
                ('previous_value', models.JSONField(blank=True, default=dict, help_text='JSON snapshot of previous configuration.')),
                ('new_value', models.JSONField(blank=True, default=dict, help_text='JSON snapshot of new configuration.')),
                ('reason', models.TextField(blank=True, help_text='Operational rationale notes.')),
                ('actor_user_id', models.CharField(blank=True, help_text='UUID of the user executing the change.', max_length=100)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(help_text='Associated employee instance.', on_delete=django.db.models.deletion.CASCADE, related_name='workforce_assignments', to='employees.employee')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'workforce assignment',
                'verbose_name_plural': 'workforce assignments',
                'ordering': ['-effective_date'],
                'indexes': [models.Index(fields=['employee', 'assignment_type'], name='idx_wfassign_emp_type'), models.Index(fields=['effective_date', 'end_date'], name='idx_wfassign_dates')],
            },
        ),
    ]
