# Generated by Django 5.2.11 on 2026-08-01 07:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier (UUIDv4) for entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the entity was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entity was last updated.')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when entity was soft-deleted, null if active.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('name', models.CharField(help_text="Human-readable role name (e.g. 'Organization Admin').", max_length=100)),
                ('code', models.CharField(help_text="Unique uppercase code (e.g. 'ORG_ADMIN').", max_length=50, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Optional description of what this role allows.')),
                ('is_system', models.BooleanField(default=False, help_text='System roles are built-in and cannot be deleted by users.')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'role',
                'verbose_name_plural': 'roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier (UUIDv4) for entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the entity was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entity was last updated.')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when entity was soft-deleted, null if active.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('organization_id', models.UUIDField(blank=True, db_index=True, help_text='Optional organization UUID scope for role assignment.', null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(help_text='Role granted to user.', on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='roles.role')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User granted this role.', on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user role',
                'verbose_name_plural': 'user roles',
                'indexes': [models.Index(fields=['user', 'role'], name='idx_userrole_user_role'), models.Index(fields=['user', 'organization_id'], name='idx_userrole_user_org')],
                'constraints': [models.UniqueConstraint(fields=('user', 'role', 'organization_id'), name='unique_user_role_org')],
            },
        ),
    ]
