# Generated by Django 5.2.11 on 2026-08-01 08:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_VERIFICATION', 'Pending Verification'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], db_index=True, default='ACTIVE', help_text='Branch operational status.', max_length=20),
        ),
        migrations.AlterField(
            model_name='department',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_VERIFICATION', 'Pending Verification'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], db_index=True, default='ACTIVE', help_text='Department operational status.', max_length=20),
        ),
        migrations.AlterField(
            model_name='designation',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_VERIFICATION', 'Pending Verification'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], db_index=True, default='ACTIVE', help_text='Designation status.', max_length=20),
        ),
        migrations.AlterField(
            model_name='holidaycalendar',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_VERIFICATION', 'Pending Verification'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], db_index=True, default='ACTIVE', help_text='Holiday calendar status.', max_length=20),
        ),
        migrations.AlterField(
            model_name='organization',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_VERIFICATION', 'Pending Verification'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], db_index=True, default='ACTIVE', help_text='Organization operational status.', max_length=20),
        ),
        migrations.AlterField(
            model_name='shift',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_VERIFICATION', 'Pending Verification'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], db_index=True, default='ACTIVE', help_text='Shift template status.', max_length=20),
        ),
        migrations.AlterField(
            model_name='team',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_VERIFICATION', 'Pending Verification'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], db_index=True, default='ACTIVE', help_text='Team status.', max_length=20),
        ),
        migrations.CreateModel(
            name='OrganizationFeatureFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier (UUIDv4) for entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the entity was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entity was last updated.')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when entity was soft-deleted, null if active.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('attendance_enabled', models.BooleanField(default=True, help_text='Toggles Attendance tracking module.')),
                ('payroll_enabled', models.BooleanField(default=True, help_text='Toggles Payroll and compensation module.')),
                ('crm_enabled', models.BooleanField(default=True, help_text='Toggles Customer Relationship Management module.')),
                ('projects_enabled', models.BooleanField(default=True, help_text='Toggles Projects and task tracking module.')),
                ('documents_enabled', models.BooleanField(default=True, help_text='Toggles Document Management module.')),
                ('ai_assistant_enabled', models.BooleanField(default=False, help_text='Toggles Nexora AI Assistant features.')),
                ('automation_enabled', models.BooleanField(default=True, help_text='Toggles Business Process Automation workflows.')),
                ('api_access_enabled', models.BooleanField(default=True, help_text='Toggles REST API external integration access.')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('organization', models.OneToOneField(help_text='Associated organization instance.', on_delete=django.db.models.deletion.PROTECT, related_name='feature_flag', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'organization feature flag',
                'verbose_name_plural': 'organization feature flags',
            },
        ),
        migrations.CreateModel(
            name='OrganizationLimit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier (UUIDv4) for entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the entity was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entity was last updated.')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when entity was soft-deleted, null if active.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('max_branches', models.PositiveIntegerField(default=10, help_text='Maximum allowed active branch locations.')),
                ('max_departments', models.PositiveIntegerField(default=25, help_text='Maximum allowed department units.')),
                ('max_teams', models.PositiveIntegerField(default=50, help_text='Maximum allowed team units.')),
                ('max_employees', models.PositiveIntegerField(default=250, help_text='Maximum allowed active employees.')),
                ('max_storage_gb', models.PositiveIntegerField(default=100, help_text='Maximum allowed document storage in GB.')),
                ('max_api_calls_per_day', models.PositiveIntegerField(default=10000, help_text='Maximum allowed daily API request calls.')),
                ('max_projects', models.PositiveIntegerField(default=50, help_text='Maximum allowed active projects.')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('organization', models.OneToOneField(help_text='Associated organization instance.', on_delete=django.db.models.deletion.PROTECT, related_name='limit', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'organization limit',
                'verbose_name_plural': 'organization limits',
            },
        ),
        migrations.CreateModel(
            name='OrganizationAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier (UUIDv4) for entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the entity was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entity was last updated.')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when entity was soft-deleted, null if active.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('event_type', models.CharField(db_index=True, help_text='Category identifier of the audit event.', max_length=100)),
                ('user_id', models.CharField(blank=True, help_text='UUID of the initiating user.', max_length=100)),
                ('user_email', models.CharField(blank=True, help_text='Email address of the initiating user.', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Client IP address.', null=True)),
                ('request_id', models.CharField(blank=True, help_text='Correlation request ID.', max_length=100)),
                ('previous_state', models.JSONField(blank=True, default=dict, help_text='Previous state values snapshot.')),
                ('new_state', models.JSONField(blank=True, default=dict, help_text='New state values snapshot.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context metadata.')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Event creation timestamp.')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='Associated organization instance.', on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'organization audit event',
                'verbose_name_plural': 'organization audit events',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['organization', 'event_type'], name='idx_orgaudit_org_event'), models.Index(fields=['organization', 'timestamp'], name='idx_orgaudit_org_time')],
            },
        ),
    ]
