# Generated by Django 5.2.11 on 2026-08-01 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_branch_status_alter_department_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationlimit',
            name='max_shifts',
            field=models.PositiveIntegerField(default=20, help_text='Maximum allowed shift templates.'),
        ),
    ]
