# Generated by Django 5.2.11 on 2026-08-01 09:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_managerassignment_workforceassignment'),
        ('organizations', '0003_organizationlimit_max_shifts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftRoster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier (UUIDv4) for entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the entity was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entity was last updated.')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when entity was soft-deleted, null if active.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('name', models.CharField(help_text='Roster display name (e.g., Q3 Engineering Shift Schedule).', max_length=255)),
                ('code', models.CharField(db_index=True, help_text='Unique roster identifier code within organization.', max_length=50)),
                ('period_type', models.CharField(choices=[('DAILY', 'Daily Planning'), ('WEEKLY', 'Weekly Planning'), ('BIWEEKLY', 'Biweekly Planning'), ('MONTHLY', 'Monthly Planning')], default='WEEKLY', help_text='Roster planning window period.', max_length=50)),
                ('start_date', models.DateField(db_index=True, help_text='Roster effective start date.')),
                ('end_date', models.DateField(db_index=True, help_text='Roster effective end date.')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft Roster'), ('PUBLISHED', 'Published Roster'), ('ARCHIVED', 'Archived Roster')], db_index=True, default='DRAFT', help_text='Roster lifecycle publication state.', max_length=50)),
                ('version', models.PositiveIntegerField(default=1, help_text='Roster revision version counter.')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='Associated Organization instance.', on_delete=django.db.models.deletion.CASCADE, related_name='shift_rosters', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'shift roster',
                'verbose_name_plural': 'shift rosters',
                'ordering': ['-start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ShiftRosterAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier (UUIDv4) for entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the entity was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entity was last updated.')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when entity was soft-deleted, null if active.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('date', models.DateField(db_index=True, help_text='Calendar date of shift assignment.')),
                ('is_override', models.BooleanField(default=False, help_text='Flag indicating manual override of default/rotation shift.')),
                ('override_reason', models.TextField(blank=True, help_text='Rationale notes if assignment is an override.')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(help_text='Assigned Employee instance.', on_delete=django.db.models.deletion.CASCADE, related_name='roster_assignments', to='employees.employee')),
                ('roster', models.ForeignKey(help_text='Parent ShiftRoster instance.', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='organizations.shiftroster')),
                ('shift', models.ForeignKey(help_text='Assigned Shift template.', on_delete=django.db.models.deletion.PROTECT, related_name='roster_assignments', to='organizations.shift')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'shift roster assignment',
                'verbose_name_plural': 'shift roster assignments',
                'ordering': ['date', 'employee'],
            },
        ),
        migrations.CreateModel(
            name='ShiftRotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier (UUIDv4) for entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the entity was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entity was last updated.')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when entity was soft-deleted, null if active.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('name', models.CharField(help_text='Rotation pattern name (e.g., 3-Shift Weekly Rotation).', max_length=255)),
                ('code', models.CharField(db_index=True, help_text='Unique rotation code within organization.', max_length=50)),
                ('rotation_type', models.CharField(choices=[('WEEKLY', 'Weekly Shift Rotation'), ('BIWEEKLY', 'Biweekly Shift Rotation'), ('MONTHLY', 'Monthly Shift Rotation'), ('CUSTOM', 'Custom Pattern Rotation')], default='WEEKLY', help_text='Rotation cycle frequency.', max_length=50)),
                ('pattern_json', models.JSONField(default=list, help_text='JSON sequence array of shift IDs or codes defining the rotation cycle.')),
                ('cycle_days', models.PositiveIntegerField(default=7, help_text='Total duration of one full rotation cycle in days.')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='Associated Organization instance.', on_delete=django.db.models.deletion.CASCADE, related_name='shift_rotations', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'shift rotation',
                'verbose_name_plural': 'shift rotations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShiftSwapRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier (UUIDv4) for entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the entity was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entity was last updated.')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when entity was soft-deleted, null if active.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this record is active.')),
                ('requester_date', models.DateField(help_text="Original date of requester's shift to swap.")),
                ('target_date', models.DateField(help_text="Target date of peer's shift to swap.")),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved by Manager / System'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', help_text='Approval workflow status of swap request.', max_length=50)),
                ('reason', models.TextField(blank=True, help_text='Rationale notes for shift swap.')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(help_text='Employee requesting the shift swap.', on_delete=django.db.models.deletion.CASCADE, related_name='initiated_shift_swaps', to='employees.employee')),
                ('target_employee', models.ForeignKey(help_text='Target employee to swap shift with.', on_delete=django.db.models.deletion.CASCADE, related_name='received_shift_swaps', to='employees.employee')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'shift swap request',
                'verbose_name_plural': 'shift swap requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='shiftroster',
            index=models.Index(fields=['organization', 'status', 'start_date'], name='idx_sroster_org_status'),
        ),
        migrations.AddConstraint(
            model_name='shiftroster',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_shiftroster_org_code'),
        ),
        migrations.AddIndex(
            model_name='shiftrosterassignment',
            index=models.Index(fields=['employee', 'date'], name='idx_srosterassign_emp_date'),
        ),
        migrations.AddConstraint(
            model_name='shiftrosterassignment',
            constraint=models.UniqueConstraint(fields=('roster', 'employee', 'date'), name='unique_srosterassign_emp_date'),
        ),
        migrations.AddConstraint(
            model_name='shiftrotation',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_shiftrotation_org_code'),
        ),
        migrations.AddIndex(
            model_name='shiftswaprequest',
            index=models.Index(fields=['requester', 'status'], name='idx_sswap_requester_status'),
        ),
    ]
